#!/usr/bin/env python3
"""Generate a TRANSIENT build-in animation variant of the medallion from the FLAT
source-of-record, WITHOUT modifying pattern.bkr.

Plain English: the owner wants to watch the medallion assemble — center first, then
each wave flying in from the rim and settling into place, wave by wave. The
`radial_assemble` animate primitive does exactly this; this script bolts it onto the
real medallion by reading the flat pattern.bkr verbatim and (a) prepending the
`animate buildin` declaration and (b) inserting the one-line `animate buildin`
reference into the pattern body right after `voids detect`. The source-of-record is
read-only here — the variant is a separate file, regenerable any time, never
committed as the pattern itself (owner-gated, #24).

The animation targets every polygon face (`[sides >= 3]`) so all 22 waves participate;
the per-face delay is driven by `faceRings` (centroid-distance bin), so the center
seats first and the rim last regardless of the DSL `layer` tags the medallion uses for
coloring.

Usage:  python3 build_medallion_buildin.py
Writes: pattern-buildin.bkr  (next to this script)
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
FLAT = HERE.parent / "iterations" / "71" / "pattern.bkr"
OUT = HERE / "pattern-buildin.bkr"

# The build-in animation declaration. Tuned for the medallion's scale (R≈100):
#   from 1.8  — each face starts 1.8× its centroid distance out along its radial axis,
#               so the outermost waves begin well off-frame and sweep inward.
#   to 0      — seated home (identity).
#   duration 1.4s, delay_per_layer 0.18s — 22 distance rings × 0.18 ≈ 4s of staggered
#               build before the last wave starts its 1.4s settle (~5.4s total).
#   easing ease_out — decelerate into the seated position (a "settling" feel).
ANIMATE_BLOCK = """# ===== TRANSIENT build-in animation (NOT part of the flat source-of-record) =====
# Generated by animate-buildin/build_medallion_buildin.py from iterations/71/pattern.bkr.
# Owner-gated (#14): the medallion assembles center-first, wave-by-wave, each face
# flying in from its own outward radial offset. delay_per_layer reads faceRings
# (centroid-distance bin) so inner waves seat before outer waves.
animate buildin
  keyframes assemble
    target [sides >= 3]
    property radial_assemble
    from 1.8
    to 0
    duration 1.4s
    delay_per_layer 0.18s
    easing ease_out

"""


def main() -> None:
    src = FLAT.read_text()

    # (a) Prepend the animate declaration ahead of the first top-level block.
    # pattern.bkr opens with a comment header then `blueprint center_star`; insert the
    # animate block immediately before `blueprint` so it's a clean top-level sibling.
    marker = "\nblueprint center_star"
    idx = src.index(marker)
    head, tail = src[:idx], src[idx:]
    out = head + "\n" + ANIMATE_BLOCK + tail.lstrip("\n")

    # (b) Insert the one-line reference into the pattern body, right after `voids detect`.
    vd = "\n  voids detect\n"
    if vd not in out:
        raise SystemExit("could not find `  voids detect` in pattern body — structure changed?")
    out = out.replace(vd, vd + "  animate buildin\n", 1)

    OUT.write_text(out)
    print(f"wrote {OUT} ({len(out.splitlines())} lines)")


if __name__ == "__main__":
    main()
