<!DOCTYPE html>
<html>
    <!-- The file in site/index.html is autogenerated using the template in src/templates/index.html! -->
    <head>
        <script type="text/javascript" src="https://d3js.org/d3.v5.min.js"></script>
        <script type="text/javascript" src="https://d3js.org/d3-color.v1.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js"></script>
        <!-- https://lodash.com/docs/4.17.15#template -->
        <!-- ======= This was auto generated: ======= -->
        <!-- This block effectively injects our ts/js as sacredPatterns through the webpack.config.js -->
        <% _.each(htmlWebpackPlugin.files.js, function(f) { %>
        <script type="text/javascript" src="<%= f %>"></script>
        <% }); %>
        <!-- ======================================== -->
    </head>
    <body>
        <div>
            <%= VERSION %>
            <%= COMMITHASH %>
            <%= BRANCH %>
        </div>

        <div id="root"></div>

        <pre id="config" contenteditable="true">
        {
            "background_theme": [
                {
                    "background": "RGBA(0,0,0,0.9)",
                    "comment": "black"
                },
                {
                    "background": "RGBA(255,255,255,0.9)",
                    "comment": "white"
                },
                {
                    "background": "RGBA(118,215,196,0.9)", 
                    "comment": "turquise"
                }
            ],
            "line_theme": [
                {
                    "stroke": "url(#invertedSvgGradient)",
                    "stroke-width": "1"
                },
                {
                    "stroke": "url(#svgGradient)",
                    "stroke-width": "1"
                },
                {
                    "stroke": "RGB(244,208,63)", 
                    "comment": "Gold"
                },
                {
                    "stroke": "RGB(192,192,192)", 
                    "comment": "Silver"
                },
                {
                    "fill": "RGBA(118,215,196,0.5)",
                    "fill": "RGBA(118,215,196,0.75)"
                }
            ]
        }
        </pre>

        <ul>
            <li><a id="download" href="#">Download SVG</a></li>
            <!--
                <li><a id="regenerate" href="#">Regenerate SVG</a></li>
                <li><a id="download-inverted" href="#">Download Inverted SVG</a></li>
            -->
        </ul>
        
        <script type="text/javascript">
            sacredPatterns.main()
        </script>
  </body>
</html>
