<!DOCTYPE html>
<html>
    <!-- The file in site/index.html is autogenerated using the template in src/templates/index.html! -->
  <head>
      <script type="text/javascript" src="https://d3js.org/d3.v5.min.js"></script>
      <script type="text/javascript" src="https://d3js.org/d3-color.v1.min.js"></script>
      <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js"></script>
      <!-- https://lodash.com/docs/4.17.15#template -->
      <!-- ======= This was auto generated: ======= -->
      <% _.each(htmlWebpackPlugin.files.js, function(f) { %>
      <script type="text/javascript" src="<%= f %>"></script>
      <% }); %>
      <!-- ======================================== -->
  </head>
  <body>

      <script type="text/javascript">
        const radius = 100;
        const maxLevels = 2;
        const size = maxLevels * 4;

        // do drawHexagonWithSurroundingNonagons but in a grid ...
        // do the whole draw outer ring so I can roteate inner ring!

        // drawCirclesRecursively();
        sacredPatterns.drawHexagonWithSurroundingNonagons(radius, size);
        // drawRotatingCircles();
        // drawDifferentPolygons();
        // drawStarGrid();
        // drawRotatedStar();
        // drawDifferentStars();
      </script>
  </body>
</html>
