#!/usr/bin/env sh
# Generate docs/decisions/LEDGER.md from decision-doc frontmatter.
#
# Why generated, not hand-curated: the 2026-06-06 coherence audit's root
# finding is that hand-maintained status drifts (the qiyas README carried a doc
# with TWO statuses on one line). A generated ledger inherits correctness from
# the frontmatter the coherence checker validates — single source of truth =
# the docs. See docs/decision-schema.md for the model + data flow.
#
# Reads ONLY structured YAML frontmatter keys (status_token, picked_option,
# tag, supersedes, superseded_by, dead_end.*) via `yq --front-matter=extract`.
# NEVER scans the markdown body, NEVER regexes the human `status:` prose line.
#
# Usage:
#   scripts/gen-decision-ledger.sh            # write LEDGER.md in this repo
#   scripts/gen-decision-ledger.sh --check    # exit 1 if LEDGER.md is stale
#
# Prereqs: yq (mikefarah v4+) and a POSIX sh. `brew install yq`.
# Exit 0 on success / in-sync; 1 on --check drift or missing prereqs.

set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
DECISIONS_DIR="$ROOT/docs/decisions"
LEDGER="$DECISIONS_DIR/LEDGER.md"
TAGS_FILE="$DECISIONS_DIR/tags.yaml"
SEED_FILE="$DECISIONS_DIR/dead-ends.seed.yaml"
README="$DECISIONS_DIR/README.md"

CHECK_MODE=0
[ "${1:-}" = "--check" ] && CHECK_MODE=1

if ! command -v yq >/dev/null 2>&1; then
  echo "gen-decision-ledger: yq not found. Install with: brew install yq" >&2
  exit 1
fi

# fm <doc> <expr> — extract a frontmatter expression, '' if null/absent.
fm() {
  result=$(yq --front-matter=extract "$2" "$1" 2>/dev/null || echo "null")
  [ "$result" = "null" ] && result=""
  printf '%s' "$result"
}

# Collect decision docs (exclude README, LEDGER, the generated file itself).
docs=$(find "$DECISIONS_DIR" -maxdepth 1 -name '*.md' \
  ! -name 'README.md' ! -name 'LEDGER.md' ! -name 'LEDGER-XREPO.md' | sort)

# --- Build the by-tag table rows. -------------------------------------------
# One row per (tag, doc). The authoritative doc per tag is the latest
# non-SUPERSEDED/REOPENED doc bearing that tag with empty superseded_by; the
# coherence checker (rule 4) guarantees at most one such doc per tag, so the
# generator just marks it.

tag_rows=""
deadend_rows=""

for doc in $docs; do
  rel="docs/decisions/$(basename "$doc")"
  tag=$(fm "$doc" '.tag')
  [ -z "$tag" ] && tag="(untagged)"
  status=$(fm "$doc" '.status_token')
  [ -z "$status" ] && status="(none)"
  picked=$(fm "$doc" '.picked_option')
  superseded_by=$(fm "$doc" '.superseded_by[0]')

  # authoritative = ACCEPTED with no superseded_by pointer
  auth="no"
  if [ "$status" = "ACCEPTED" ] && [ -z "$superseded_by" ]; then
    auth="yes"
  fi

  pick_disp="$picked"
  [ -z "$pick_disp" ] && pick_disp="—"
  sup_disp="$superseded_by"
  [ -z "$sup_disp" ] && sup_disp="—"

  tag_rows="${tag_rows}${tag}\t${rel}\t${status}\t${pick_disp}\t${auth}\t${sup_disp}\n"

  # dead_end block on this doc?
  de_approach=$(fm "$doc" '.dead_end.approach')
  if [ -n "$de_approach" ]; then
    de_verdict=$(fm "$doc" '.dead_end.verdict')
    de_use=$(fm "$doc" '.dead_end.use_instead')
    [ -z "$de_use" ] && de_use="—"
    de_killed=$(fm "$doc" '.dead_end.killed_by')
    [ -z "$de_killed" ] && de_killed="$rel"
    de_prior=$(fm "$doc" '.dead_end.prior_art')
    [ -n "$de_prior" ] && de_use="$de_use (prior-art: $de_prior)"
    deadend_rows="${deadend_rows}${de_approach}\t${de_verdict}\t${de_killed}\t${de_use}\n"
  fi
done

# --- Fold in transcript-only dead-ends from the seed file. -------------------
if [ -f "$SEED_FILE" ]; then
  n=$(yq '.dead_ends | length' "$SEED_FILE" 2>/dev/null || echo 0)
  [ -z "$n" ] && n=0
  i=0
  while [ "$i" -lt "$n" ]; do
    a=$(yq ".dead_ends[$i].approach" "$SEED_FILE")
    v=$(yq ".dead_ends[$i].verdict" "$SEED_FILE")
    k=$(yq ".dead_ends[$i].killed_by // \"transcript\"" "$SEED_FILE")
    u=$(yq ".dead_ends[$i].use_instead // \"—\"" "$SEED_FILE")
    p=$(yq ".dead_ends[$i].prior_art // \"\"" "$SEED_FILE")
    [ -n "$p" ] && [ "$p" != "null" ] && u="$u (prior-art: $p)"
    deadend_rows="${deadend_rows}${a}\t${v}\t${k}\t${u}\n"
    i=$((i + 1))
  done
fi

# --- Render LEDGER.md (deterministic: sorted rows). -------------------------
render() {
  printf '<!-- GENERATED by scripts/gen-decision-ledger.sh — do not edit. Run `make ledger`. -->\n'
  printf '# Decision LEDGER\n\n'
  printf 'The consultable answer to *"what'\''s decided / what'\''s dead / which doc is\n'
  printf 'authoritative per problem-tag?"* Generated from decision-doc frontmatter —\n'
  printf 'it cannot drift from the docs. Consult this BEFORE re-deciding a tagged\n'
  printf 'problem (present-options skill §0). Schema: `docs/decision-schema.md`.\n\n'

  printf '## By problem-tag\n\n'
  printf '| tag | doc | status | picked | authoritative | superseded-by |\n'
  printf '|-----|-----|--------|--------|---------------|---------------|\n'
  printf '%b' "$tag_rows" | sort | while IFS="$(printf '\t')" read -r tag rel status picked auth sup; do
    [ -z "$tag" ] && continue
    authmark="—"
    [ "$auth" = "yes" ] && authmark="★"
    printf '| `%s` | %s | %s | %s | %s | %s |\n' "$tag" "$rel" "$status" "$picked" "$authmark" "$sup"
  done
  printf '\n_★ = the live authoritative doc for that tag (ACCEPTED, not superseded)._\n\n'

  printf '## Dead-ends (do not retry)\n\n'
  printf '| approach | verdict | killed-by | use-instead / prior-art |\n'
  printf '|----------|---------|-----------|-------------------------|\n'
  if [ -n "$deadend_rows" ]; then
    printf '%b' "$deadend_rows" | sort | while IFS="$(printf '\t')" read -r a v k u; do
      [ -z "$a" ] && continue
      printf '| %s | %s | %s | %s |\n' "$a" "$v" "$k" "$u"
    done
  else
    printf '| _(none recorded yet)_ | | | |\n'
  fi
  printf '\n_Verdict: DEAD = confirmed-dead, use the replacement · REFUTED = the\n'
  printf 'dead-end belief was wrong (solvable) · OPEN = open-in-field. See\n'
  printf '`docs/decision-schema.md`._\n'
}

# --- Render README.md — a frontmatter-derived index (replaces the hand- ------
# maintained list whose prose status drifted from frontmatter; the qiyas
# README once carried a doc with TWO statuses on one line — audit §6.6).
render_readme() {
  printf '<!-- GENERATED by scripts/gen-decision-ledger.sh — do not edit. Run `make ledger`. -->\n'
  printf '# Decision docs\n\n'
  printf 'Authored via the `present-options` skill (sacred-patterns). This index is\n'
  printf 'generated from each doc'\''s structured frontmatter so its status cannot\n'
  printf 'drift from the doc. For the "authoritative-per-tag / dead-ends" view see\n'
  printf '[`LEDGER.md`](LEDGER.md); for the schema see\n'
  printf '[`../decision-schema.md`](../decision-schema.md).\n\n'
  printf '| date — doc | status | picked | tag |\n'
  printf '|------------|--------|--------|-----|\n'
  for doc in $docs; do
    base=$(basename "$doc")
    date=$(printf '%s' "$base" | cut -c1-10)
    slug=$(printf '%s' "$base" | cut -c12- | sed 's/\.md$//')
    status=$(fm "$doc" '.status_token'); [ -z "$status" ] && status="(none)"
    picked=$(fm "$doc" '.picked_option'); [ -z "$picked" ] && picked="—"
    tag=$(fm "$doc" '.tag'); [ -z "$tag" ] && tag="(untagged)"
    printf '| %s — [%s](%s) | %s | %s | `%s` |\n' "$date" "$slug" "$base" "$status" "$picked" "$tag"
  done
}

if [ "$CHECK_MODE" -eq 1 ]; then
  rc=0
  tmp=$(mktemp)
  render >"$tmp"
  if [ ! -f "$LEDGER" ] || ! diff -q "$LEDGER" "$tmp" >/dev/null 2>&1; then
    echo "gen-decision-ledger: $LEDGER is STALE. Run: make ledger" >&2
    diff "$LEDGER" "$tmp" >&2 2>/dev/null || true
    rc=1
  fi
  rtmp=$(mktemp)
  render_readme >"$rtmp"
  if [ ! -f "$README" ] || ! diff -q "$README" "$rtmp" >/dev/null 2>&1; then
    echo "gen-decision-ledger: $README is STALE. Run: make ledger" >&2
    rc=1
  fi
  rm -f "$tmp" "$rtmp"
  [ "$rc" -eq 0 ] && echo "OK: LEDGER.md + README.md in sync with decision-doc frontmatter."
  exit "$rc"
fi

render >"$LEDGER"
render_readme >"$README"
echo "Wrote $LEDGER and $README"
