#!/usr/bin/env sh
# Generate docs/decisions/LEDGER-XREPO.md — the cross-repo roll-up of decided /
# dead / authoritative-per-tag across qiyas + bikar + sacred-patterns.
#
# Why a cross-repo roll-up: problem-tags span repos (face-class-identity lives
# in both qiyas and bikar; svg-direct's spine crosses qiyas + SP). A future
# session asking "has this tag been decided anywhere?" needs one place that
# joins all three repos' frontmatter. The per-repo LEDGER.md answers
# within-repo; this answers across.
#
# Reads ONLY structured frontmatter keys via `yq --front-matter=extract`.
# Assumes the three repos are siblings (../qiyas, ../bikar, . for SP). Skips
# any repo whose docs/decisions/ is absent.
#
# Usage: scripts/gen-decision-ledger-xrepo.sh [--check]
# Prereqs: yq (mikefarah v4+). `brew install yq`. Exit 0 ok / 1 stale-or-missing.

set -eu

SP_ROOT=$(cd "$(dirname "$0")/.." && pwd)
GIT_ROOT=$(cd "$SP_ROOT/.." && pwd)
LEDGER="$SP_ROOT/docs/decisions/LEDGER-XREPO.md"

CHECK_MODE=0
[ "${1:-}" = "--check" ] && CHECK_MODE=1

if ! command -v yq >/dev/null 2>&1; then
  echo "gen-decision-ledger-xrepo: yq not found. Install: brew install yq" >&2
  exit 1
fi

fm() {
  result=$(yq --front-matter=extract "$2" "$1" 2>/dev/null || echo "null")
  [ "$result" = "null" ] && result=""
  printf '%s' "$result"
}

rows=""
for repo in qiyas bikar sacred-patterns; do
  dir="$GIT_ROOT/$repo/docs/decisions"
  [ -d "$dir" ] || continue
  for doc in $(find "$dir" -maxdepth 1 -name '*.md' \
    ! -name 'README.md' ! -name 'LEDGER.md' ! -name 'LEDGER-XREPO.md' | sort); do
    tag=$(fm "$doc" '.tag')
    [ -z "$tag" ] && continue   # untagged docs don't roll up (pre-backfill)
    status=$(fm "$doc" '.status_token')
    [ -z "$status" ] && status="(none)"
    picked=$(fm "$doc" '.picked_option')
    [ -z "$picked" ] && picked="—"
    superseded_by=$(fm "$doc" '.superseded_by[0]')
    auth="—"
    if [ "$status" = "ACCEPTED" ] && [ -z "$superseded_by" ]; then
      auth="★"
    fi
    rel="$repo/docs/decisions/$(basename "$doc")"
    rows="${rows}${tag}\t${repo}\t${rel}\t${status}\t${picked}\t${auth}\n"
  done
done

render() {
  printf '<!-- GENERATED by scripts/gen-decision-ledger-xrepo.sh — do not edit. -->\n'
  printf '# Cross-repo Decision LEDGER\n\n'
  printf 'Decided / dead / authoritative-per-tag joined across qiyas + bikar +\n'
  printf 'sacred-patterns. Grouped by problem-tag (shared vocabulary in each\n'
  printf 'repo'\''s `docs/decisions/tags.yaml`). For within-repo detail see that\n'
  printf 'repo'\''s `LEDGER.md`. Schema: `docs/decision-schema.md`.\n\n'
  printf '| tag | repo | doc | status | picked | authoritative |\n'
  printf '|-----|------|-----|--------|--------|---------------|\n'
  if [ -n "$rows" ]; then
    printf '%b' "$rows" | sort | while IFS="$(printf '\t')" read -r tag repo rel status picked auth; do
      [ -z "$tag" ] && continue
      printf '| `%s` | %s | %s | %s | %s | %s |\n' "$tag" "$repo" "$rel" "$status" "$picked" "$auth"
    done
  else
    printf '| _(no tagged docs yet — run after backfill)_ | | | | | |\n'
  fi
  printf '\n_★ = live authoritative doc for that tag in that repo._\n'
}

if [ "$CHECK_MODE" -eq 1 ]; then
  tmp=$(mktemp)
  render >"$tmp"
  if [ ! -f "$LEDGER" ] || ! diff -q "$LEDGER" "$tmp" >/dev/null 2>&1; then
    echo "gen-decision-ledger-xrepo: $LEDGER is STALE. Run the generator." >&2
    rm -f "$tmp"
    exit 1
  fi
  rm -f "$tmp"
  echo "OK: LEDGER-XREPO.md in sync."
  exit 0
fi

render >"$LEDGER"
echo "Wrote $LEDGER"
