#!/usr/bin/env sh
# Point git at this repo's TRACKED hook directory.
#
# WHY THIS EXISTS. `core.hooksPath` used to be `.husky/_` — husky's generated
# shim directory, which is untracked and regenerated by `npm install`. That is
# fine in the checkout where npm ran and nowhere else. Measured 2026-08-17 in a
# fresh linked worktree:
#
#   $ git commit -m "..."        # a file that fails eslint AND has no scan
#   [detached HEAD d2d6ce7] ...  # exit 0, and not one line of hook output
#   $ sh .husky/pre-commit       # the same hook, run by hand, same staged file
#   exit 1
#
# The gate was live the whole time. Only the wiring was dead, and it failed the
# way that costs the most: silently, reporting success. This repo has no CI, so
# a hook that does not run is the entire gate not running.
#
# THE FIX IS THE DIRECTORY, NOT THE TOOL. `.husky/pre-commit` and
# `.husky/pre-push` are tracked; only husky's `_` indirection was not. Pointing
# `core.hooksPath` straight at `.husky` runs the same two tracked files with no
# generated directory in between, so every clone and every worktree that has
# the files has the hooks. husky's `prepare: husky` step is gone with it —
# leaving it would reset `core.hooksPath` back to `.husky/_` on the next
# install and quietly undo this.
#
# Run by `npm install` (via `prepare`) and by hand as `npm run setup-hooks`.
set -e

root=$(git rev-parse --show-toplevel)
cd "$root"

git config core.hooksPath .husky

missing=""
for hook in pre-commit pre-push; do
  if [ ! -f ".husky/$hook" ]; then
    missing="$missing .husky/$hook(absent)"
  elif [ ! -x ".husky/$hook" ]; then
    missing="$missing .husky/$hook(not executable)"
  fi
done

if [ -n "$missing" ]; then
  echo "hooks: core.hooksPath -> .husky, but:$missing" >&2
  echo "       git runs a hook only if it is executable, and says nothing when" >&2
  echo "       it is not — which is the failure this script exists to end." >&2
  exit 1
fi

echo "hooks: core.hooksPath -> .husky (tracked, so it survives a fresh worktree)"
echo "  pre-commit = $(command -v gitleaks >/dev/null 2>&1 && echo 'gitleaks +' || echo 'gitleaks MISSING (blocks) +') eslint/tsc on src/ts + decision coherence"
echo "  pre-push   = gitleaks full history (this repo has no CI)"
echo "  verify any time: npm run test:hooks"
