#!/usr/bin/env python3
"""Serve the session's review experiences on localhost — one front door.

Plain English: this is the CLI the owner runs to review a reconstruction
session. The landing page is a HUB that reads session.json and says, in
words, what needs the owner's eyes today (the wave plan? the colours?),
with one link per item. From there:

- /plan — the wave-plan STUDIO (wave-plan.html, generated by plan-waves.py):
  click any shape, see its wave + flower, fix groupings; "Apply my fixes"
  POSTs here, we persist wave-plan-overrides.json and re-run plan-waves.py.
  The page's "The plan looks right" button records the gate verdict in
  session.json — no chat transcription.
- /palette — the colour gate: the swatch sheet beside the reference;
  "These colours are right" records palette agreement; a note box captures
  corrections (auto-saved, with a visible "saved" confirmation).

Usage:
    /Users/omareid/Workspace/git/qiyas/.venv/bin/python tools/wave-plan-server.py \
        /Users/omareid/Dropbox/Data/sacred-patterns/bikar-medallion-10 \
        --center 386 361 --diameter 738 [--port 8765]

Then open the printed URL. Ctrl-C stops it.

Why a server and not a static page (owner, 2026-06-11): "this should not be
static html, but rather cli commands that runs localhost" — fixes must
persist and re-flow through the plan without the owner shuttling JSON files.
Why a hub (owner, 2026-06-11, review-experience audit —
docs/review-experience-audit.md): four review surfaces with four launch
mechanisms meant nobody could ask "what's waiting for my review?"; the
session.json knows, so the front door reads it back in plain language.
"""

from __future__ import annotations

import argparse
import html
import json
import subprocess
import sys
from datetime import date
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

# Mirrors the design tokens in plan-waves.py's studio CSS — one design system
# across every page the owner touches (hub, plan, palette).
HUB_CSS = """
 :root {
   --paper: #F6F3EC; --card: #FFFFFF; --ink: #202A36; --muted: #7A746A;
   --line: #E4DFD3; --accent: #19599C; --accent-soft: #EAF1F8;
   --apply: #D4501E; --agree: #1F7A45;
   --shadow: 0 1px 2px rgba(32,42,54,.05), 0 10px 28px rgba(32,42,54,.08);
   --serif: Charter, 'Iowan Old Style', Georgia, serif;
 }
 * { box-sizing: border-box; }
 body { font-family: 'Avenir Next', Seravek, 'Helvetica Neue', -apple-system, sans-serif;
        margin: 0; background: var(--paper); color: var(--ink);
        -webkit-font-smoothing: antialiased; }
 header { padding: 20px 24px 14px; background: var(--card);
          border-bottom: 1px solid var(--line); }
 h1 { font-family: var(--serif); font-weight: 600; font-size: 25px;
      letter-spacing: .1px; margin: 0 0 6px; }
 p { margin: 5px 0; }
 .muted { color: var(--muted); font-size: 13.5px; line-height: 1.55; }
 main { max-width: 760px; margin: 0 auto; padding: 12px 24px 32px; }
 .gate { background: var(--card); border: 1px solid var(--line); border-radius: 14px;
         padding: 18px 20px; margin: 16px 0; font-size: 15.5px;
         box-shadow: var(--shadow);
         animation: rise .45s ease both; }
 .gate:nth-child(2) { animation-delay: .08s; }
 .gate:nth-child(3) { animation-delay: .16s; }
 @keyframes rise { from { opacity: 0; transform: translateY(8px); } }
 .gate h2 { font-family: var(--serif); font-size: 19px; margin: 0 0 6px; }
 .gate.done { opacity: .65; }
 .badge { font-size: 12px; font-weight: 600; letter-spacing: .04em;
          padding: 3px 11px; border-radius: 999px;
          color: #fff; margin-left: 10px; vertical-align: 3px; }
 .badge.open { background: var(--apply); } .badge.done { background: var(--agree); }
 a.go { display: inline-flex; align-items: center; margin-top: 10px;
        font-size: 15px; font-weight: 500;
        background: var(--accent); color: #fff; text-decoration: none;
        height: 36px; padding: 0 18px; border-radius: 999px;
        transition: transform .15s ease, box-shadow .15s ease; }
 a.go:hover { transform: translateY(-1px); box-shadow: var(--shadow); }
 ul { margin: 6px 0; padding-left: 22px; }
"""

PALETTE_HTML = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Do the colours look right?</title>
<style>__CSS__
 img { max-width: 100%; display: block; border-radius: 10px; }
 button { font: inherit; font-size: 15px; font-weight: 600; color: #fff;
          display: inline-flex; align-items: center; height: 36px;
          padding: 0 18px; border-radius: 999px; border: 1px solid var(--agree);
          background: var(--agree); cursor: pointer;
          transition: transform .15s ease, box-shadow .15s ease; }
 button:hover { transform: translateY(-1px); box-shadow: var(--shadow); }
 button:disabled { opacity: .65; cursor: default; transform: none; box-shadow: none; }
 textarea { width: 100%; font: inherit; font-size: 14.5px; padding: 10px 12px;
            border-radius: 10px; border: 1px solid var(--line);
            background: var(--card); color: var(--ink); resize: vertical; }
 textarea:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
 #saved { color: var(--agree); font-size: 14px; margin-left: 10px; }
</style></head><body>
<header>
 <h1>Do the colours look right?</h1>
 <p class="muted">These are the colours we measured from your picture — each
  swatch shows one colour and how much of the picture uses it. We will only
  paint with these. <a href="/">Back to your review list</a></p>
</header>
<main>
 <div class="gate"><img src="/swatch-sheet.png" alt="the colours next to your picture"></div>
 <div class="gate" id="gatebox">
  <h2>Your verdict</h2>
  <p><button id="agree">These colours are right</button>
     <span id="saved"></span></p>
  <p class="muted">Anything off? Say it in your own words — "the dark blue is
   too dark", "there should be a gold" — it saves as you type.</p>
  <textarea id="note" rows="3" placeholder="The dark blue is too dark…">__NOTE__</textarea>
  <span id="notesaved" class="muted"></span>
 </div>
</main>
<script>
 const agreed = __AGREED__;
 const agreeBtn = document.getElementById('agree');
 if (agreed) { agreeBtn.disabled = true; agreeBtn.textContent = 'Recorded — these colours are agreed ✓'; }
 agreeBtn.addEventListener('click', async () => {
   agreeBtn.disabled = true;
   try {
     await fetch('/api/palette-agree', { method: 'POST' });
     agreeBtn.textContent = 'Recorded — these colours are agreed ✓';
     document.getElementById('saved').textContent = 'saved ✓';
   } catch (e) {
     agreeBtn.disabled = false;
     document.getElementById('saved').textContent = "couldn't save — try again";
   }
 });
 let t = null;
 document.getElementById('note').addEventListener('input', e => {
   clearTimeout(t);
   document.getElementById('notesaved').textContent = 'saving…';
   t = setTimeout(async () => {
     try {
       await fetch('/api/palette-note', { method: 'POST', body: e.target.value });
       document.getElementById('notesaved').textContent = 'saved ✓';
     } catch { document.getElementById('notesaved').textContent = "couldn't save — try again"; }
   }, 600);
 });
</script>
</body></html>"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("session_dir", type=Path)
    ap.add_argument(
        "--center",
        nargs=2,
        type=float,
        default=None,
        help="override the planner's auto-detected medallion center",
    )
    ap.add_argument(
        "--diameter",
        type=float,
        default=None,
        help="override the planner's auto-detected medallion diameter",
    )
    ap.add_argument("--port", type=int, default=8765)
    args = ap.parse_args()

    session_dir = args.session_dir.resolve()
    analysis_dir = session_dir / "input" / "reference-analysis"
    plan_dir = (analysis_dir / "wave-plan").resolve()
    session_json = session_dir / "session.json"
    note_path = analysis_dir / "palette-feedback.txt"
    tools_dir = Path(__file__).resolve().parent

    def regen() -> None:
        # Re-run the planner with the SAME center/diameter (or let it
        # auto-detect, same as the first run); it auto-loads
        # wave-plan-overrides.json from plan_dir, so owner fixes flow through
        # grouping, flower seating, validation, and every picture.
        cmd = [sys.executable, str(tools_dir / "plan-waves.py"), str(session_dir)]
        if args.center is not None:
            cmd += ["--center", str(args.center[0]), str(args.center[1])]
        if args.diameter is not None:
            cmd += ["--diameter", str(args.diameter)]
        subprocess.run(cmd, check=True)

    def session() -> dict:
        return json.loads(session_json.read_text())

    def save_session(s: dict) -> None:
        session_json.write_text(json.dumps(s, indent=2) + "\n")

    def hub_html() -> str:
        # The front door: read session.json's stage gates and say, in plain
        # words, what needs the owner's eyes — one card per gate, done gates
        # dimmed. No jargon, no Q-numbers, no file paths in the headline.
        s = session()
        gates = s.get("stage_gates", {})
        wp = gates.get("structure", {}).get("wave_plan", {})
        plan_agreed = bool(wp.get("agreed"))
        palette_agreed = bool(gates.get("color", {}).get("palette_agreed"))
        adjudications = wp.get("open_adjudications", "")

        todo = []
        if not plan_agreed:
            extra = ""
            if adjudications:
                extra = (
                    "<p class='muted'>Two groupings we weren't sure about — "
                    "please check them on the plan page (click a shape in the "
                    "group, then move its whole group if we got it wrong):</p>"
                    f"<ul class='muted'><li>{html.escape(adjudications)}</li></ul>"
                )
            todo.append(
                "<div class='gate'><h2>1 — The building plan"
                "<span class='badge open'>needs you</span></h2>"
                "<p>We broke your picture into a few flowers, copied in waves. "
                "Look it over, fix any shape that's in the wrong group, and "
                "press “The plan looks right” when you agree — we "
                "don't start building until then.</p>"
                f"{extra}"
                "<a class='go' href='/plan'>Open the plan</a></div>"
            )
        else:
            todo.append(
                "<div class='gate done'><h2>1 — The building plan"
                "<span class='badge done'>agreed ✓</span></h2>"
                "<p>You agreed to the plan — building is underway. You can "
                "still <a href='/plan'>look at it</a>.</p></div>"
            )
        if (analysis_dir / "swatch-sheet.png").exists():
            if not palette_agreed:
                todo.append(
                    "<div class='gate'><h2>2 — The colours"
                    "<span class='badge open'>needs you</span></h2>"
                    "<p>These are the exact colours we'll paint with. One "
                    "look — are they right?</p>"
                    "<a class='go' href='/palette'>Check the colours</a></div>"
                )
            else:
                todo.append(
                    "<div class='gate done'><h2>2 — The colours"
                    "<span class='badge done'>agreed ✓</span></h2>"
                    "<p>Colours agreed. You can still "
                    "<a href='/palette'>see them</a>.</p></div>"
                )
        n_open = sum("needs you" in t for t in todo)
        head = (
            f"{n_open} thing{'s' if n_open != 1 else ''} need your eyes today."
            if n_open
            else "Nothing waiting on you right now — everything you've agreed to is underway."
        )
        return (
            "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            f"<title>Your review list</title><style>{HUB_CSS}</style></head><body>"
            f"<header><h1>Your review list</h1><p>{head}</p>"
            f"<p class='muted'>Pattern: {html.escape(s.get('name', ''))}</p></header>"
            f"<main>{''.join(todo)}</main></body></html>"
        )

    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *a, **k):
            super().__init__(*a, directory=str(plan_dir), **k)

        # Pictures change on every Apply; the browser must never show a stale
        # wave/flower PNG after a regeneration.
        def end_headers(self):
            self.send_header("Cache-Control", "no-store")
            super().end_headers()

        def _send_html(self, body: str) -> None:
            data = body.encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def _send_ok(self) -> None:
            body = b'{"ok": true}'
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            if self.path in ("/", "/index.html"):
                self._send_html(hub_html())
                return
            if self.path == "/plan":
                self.path = "/wave-plan.html"
            elif self.path == "/palette":
                gates = session().get("stage_gates", {})
                agreed = bool(gates.get("color", {}).get("palette_agreed"))
                note = note_path.read_text() if note_path.exists() else ""
                self._send_html(
                    PALETTE_HTML.replace("__CSS__", HUB_CSS)
                    .replace("__AGREED__", json.dumps(agreed))
                    .replace("__NOTE__", html.escape(note))
                )
                return
            elif self.path == "/swatch-sheet.png":
                # The swatch sheet lives one level above the served plan dir.
                data = (analysis_dir / "swatch-sheet.png").read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            super().do_GET()

        def _read_body(self) -> bytes:
            n = int(self.headers.get("Content-Length", 0))
            return self.rfile.read(n)

        def do_POST(self):
            if self.path == "/api/overrides":
                data = json.loads(self._read_body())
                # Drop empty maps so a fully-undone state deletes cleanly.
                data = {k: v for k, v in data.items() if v}
                ov = plan_dir / "wave-plan-overrides.json"
                if data:
                    ov.write_text(json.dumps(data, indent=2))
                elif ov.exists():
                    ov.unlink()
                try:
                    regen()
                except subprocess.CalledProcessError as e:
                    self.send_error(500, f"plan regeneration failed: {e}")
                    return
                self._send_ok()
            elif self.path == "/api/agree":
                # The wave-plan gate verdict, recorded where the loop reads it
                # (session.json) — no chat transcription step.
                self._read_body()
                s = session()
                wp = s["stage_gates"]["structure"]["wave_plan"]
                wp["agreed"] = True
                wp["agreed_date"] = date.today().isoformat()
                save_session(s)
                self._send_ok()
            elif self.path == "/api/palette-agree":
                self._read_body()
                s = session()
                c = s["stage_gates"]["color"]
                c["palette_agreed"] = True
                c["approved_date"] = date.today().isoformat()
                save_session(s)
                self._send_ok()
            elif self.path == "/api/palette-note":
                note = self._read_body().decode()
                if note.strip():
                    note_path.write_text(note)
                elif note_path.exists():
                    note_path.unlink()
                self._send_ok()
            else:
                self.send_error(404)

        def log_message(self, fmt, *a):  # quiet: one line per request is noise
            pass

    if not (plan_dir / "wave-plan.html").exists():
        print("no wave-plan.html yet — generating the plan first…")
        regen()

    print(f"Review hub: http://127.0.0.1:{args.port}/")
    print("It lists what needs your eyes; each item links to its page. Ctrl-C to stop.")
    HTTPServer(("127.0.0.1", args.port), Handler).serve_forever()


if __name__ == "__main__":
    main()
