#!/usr/bin/env python3
"""Serve the wave-plan experience on localhost with live group fixing.

Plain English: this is the CLI the owner runs to review and FIX the wave plan
in a browser. The page (wave-plan.html, generated by plan-waves.py) lets the
owner click any shape, see its wave + flower, and move it; pressing "Apply my
fixes" POSTs the overrides here, this server writes them to
wave-plan-overrides.json and re-runs plan-waves.py, so every picture, count,
and validation regenerates with the owner's corrections baked in. No download
dance, no manual re-runs.

Usage:
    /Users/omareid/Workspace/git/qiyas/.venv/bin/python tools/wave-plan-server.py \
        /Users/omareid/Dropbox/Data/sacred-patterns/bikar-medallion-10 \
        --center 386 361 --diameter 738 [--port 8765]

Then open the printed URL. Ctrl-C stops it.

Why a server and not a static page (owner, 2026-06-11): "this should not be
static html, but rather cli commands that runs localhost" — fixes must
persist and re-flow through the plan without the owner shuttling JSON files.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("session_dir", type=Path)
    ap.add_argument("--center", nargs=2, type=float, required=True)
    ap.add_argument("--diameter", type=float, required=True)
    ap.add_argument("--port", type=int, default=8765)
    args = ap.parse_args()

    plan_dir = (
        args.session_dir / "input" / "reference-analysis" / "wave-plan"
    ).resolve()
    tools_dir = Path(__file__).resolve().parent

    def regen() -> None:
        # Re-run the planner with the SAME center/diameter; it auto-loads
        # wave-plan-overrides.json from plan_dir, so owner fixes flow through
        # grouping, flower seating, validation, and every picture.
        subprocess.run(
            [
                sys.executable,
                str(tools_dir / "plan-waves.py"),
                str(args.session_dir),
                "--center",
                str(args.center[0]),
                str(args.center[1]),
                "--diameter",
                str(args.diameter),
            ],
            check=True,
        )

    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *a, **k):
            super().__init__(*a, directory=str(plan_dir), **k)

        # Pictures change on every Apply; the browser must never show a stale
        # wave/flower PNG after a regeneration.
        def end_headers(self):
            self.send_header("Cache-Control", "no-store")
            super().end_headers()

        def do_GET(self):
            if self.path in ("/", "/index.html"):
                self.path = "/wave-plan.html"
            super().do_GET()

        def do_POST(self):
            if self.path != "/api/overrides":
                self.send_error(404)
                return
            n = int(self.headers.get("Content-Length", 0))
            data = json.loads(self.rfile.read(n))
            # Drop empty maps so a fully-undone state deletes cleanly.
            data = {k: v for k, v in data.items() if v}
            ov = plan_dir / "wave-plan-overrides.json"
            if data:
                ov.write_text(json.dumps(data, indent=2))
            elif ov.exists():
                ov.unlink()
            try:
                regen()
            except subprocess.CalledProcessError as e:
                self.send_error(500, f"plan regeneration failed: {e}")
                return
            body = b'{"ok": true}'
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, fmt, *a):  # quiet: one line per request is noise
            pass

    if not (plan_dir / "wave-plan.html").exists():
        print("no wave-plan.html yet — generating the plan first…")
        regen()

    print(f"Wave-plan studio: http://127.0.0.1:{args.port}/")
    print("Click any shape to see its wave + flower and fix it. Ctrl-C to stop.")
    HTTPServer(("127.0.0.1", args.port), Handler).serve_forever()


if __name__ == "__main__":
    main()
