#!/usr/bin/env python3
"""Serve the session's review experiences on localhost — one front door.

Plain English: this is the CLI the owner runs to review a reconstruction
session. The landing page is a HUB that reads session.json and says, in
words, what needs the owner's eyes today (the wave plan? the colours?),
with one link per item. From there:

- /plan — the wave-plan STUDIO (wave-plan.html, generated by plan-waves.py):
  click any shape, see its wave + flower, fix groupings; "Apply my fixes"
  POSTs here, we persist wave-plan-overrides.json and re-run plan-waves.py.
  The page's "The plan looks right" button records the gate verdict in
  session.json — no chat transcription.
- /palette — the colour gate: the swatch sheet beside the reference;
  "These colours are right" records palette agreement; a note box captures
  corrections (auto-saved, with a visible "saved" confirmation).
- /iterate — the BUILD progress view, companion to /plan: same wave list,
  but each built wave shows OUR render beside the reference (the per-wave
  gate side-by-side from wave-diff.py), with built/building/not-started
  status read from session.json's stage_gates.structure.waves_passed.
  Waves not yet built show the plan view's wave picture, dimmed.
- /slides — the same build as a reveal.js slideshow: title slide with the
  progress strip, one slide per PASSED wave (its gate side-by-side +
  plain-language caption), closing slide of current best vs reference.
  Reads session.json per request, so a newly passed wave appears with zero
  regeneration. reveal.js loads from the jsdelivr CDN (needs internet).

Usage:
    /Users/omareid/Workspace/git/qiyas/.venv/bin/python tools/wave-plan-server.py \
        /Users/omareid/Dropbox/Data/sacred-patterns/bikar-medallion-10 \
        --center 386 361 --diameter 738 [--port 8765]

Then open the printed URL. Ctrl-C stops it.

Why a server and not a static page (owner, 2026-06-11): "this should not be
static html, but rather cli commands that runs localhost" — fixes must
persist and re-flow through the plan without the owner shuttling JSON files.
Why a hub (owner, 2026-06-11, review-experience audit —
docs/review-experience-audit.md): four review surfaces with four launch
mechanisms meant nobody could ask "what's waiting for my review?"; the
session.json knows, so the front door reads it back in plain language.
"""

from __future__ import annotations

import argparse
import html
import json
import subprocess
import sys
from datetime import date
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

# Mirrors the design tokens in plan-waves.py's studio CSS — one design system
# across every page the owner touches (hub, plan, palette).
# The /iterate per-wave feedback wiring: Approve / Needs-work toggle each wave's
# verdict, and the comment box saves on its own (debounced) AND rides along with
# whichever button is clicked, so a "Needs work" + note posts as one fix request
# the loop reads from session.json. No build step — vanilla JS injected inline.
ITERATE_JS = r"""
function post(wave, state, note) {
  // fetch() does NOT reject on a 4xx/5xx — it resolves with res.ok=false. So
  // we throw on a non-OK status ourselves; otherwise a real server error
  // would silently show "recorded ✓" while nothing was saved.
  return fetch('/api/wave-verdict', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ wave: wave, state: state, note: note }),
  }).then(function (res) {
    if (!res.ok) throw new Error('HTTP ' + res.status);
    return res;
  });
}
document.querySelectorAll('.verdict').forEach(function (box) {
  const wave = box.getAttribute('data-wave');
  const approve = box.querySelector('.approve');
  const deny = box.querySelector('.deny');
  const note = box.querySelector('.vnote');
  const saved = box.querySelector('.vsaved');
  // Reflect the server-rendered state onto the buttons.
  const card = document.querySelector("[data-wave-card='" + wave + "']");
  if (card && card.querySelector('.badge.ok')) approve.classList.add('active');
  if (card && card.querySelector('.badge.no')) deny.classList.add('active');

  function status(msg, kind) {
    saved.textContent = msg;
    saved.classList.remove('ok', 'err', 'wait');
    if (kind) saved.classList.add(kind);
  }

  // The owner reviews from a long-lived tab. If the portal server restarts
  // (a fresh process, a new port, a brief down window), an in-flight save
  // would reject — a hard "couldn't save" dead-end. Instead we keep ONE
  // pending value per card and retry it with backoff until the server is
  // reachable again, showing "reconnecting…" meanwhile. A newer click/edit
  // while reconnecting overwrites the pending value (we only ever land the
  // latest), so the owner never loses their most recent intent.
  let pending = null;     // {state, note, okMsg} we still owe the server
  let retrying = false;   // a backoff loop is already running
  let backoff = 1000;     // ms; doubles per failure, capped

  function flush() {
    if (!pending) { retrying = false; return; }
    const job = pending;
    post(wave, job.state, job.note).then(function () {
      // Only clear if no newer edit landed while this request was in flight.
      if (pending === job) { pending = null; status(job.okMsg, 'ok'); }
      retrying = false; backoff = 1000;
      if (pending) flush();           // a newer value queued mid-flight
    }).catch(function () {
      retrying = true;
      status('reconnecting…', 'wait');
      setTimeout(flush, backoff);
      backoff = Math.min(backoff * 2, 5000);
    });
  }

  function save(state, note, okMsg) {
    pending = { state: state, note: note, okMsg: okMsg };
    if (retrying) return;             // backoff loop will pick up the new value
    status('saving…');
    flush();
  }

  function setVerdict(state) {
    approve.classList.toggle('active', state === 'approved');
    deny.classList.toggle('active', state === 'denied');
    save(state, note.value, state === 'approved'
      ? 'recorded — approved ✓'
      : 'recorded — we\'ll work on it ✓');
  }
  approve.addEventListener('click', function () { setVerdict('approved'); });
  deny.addEventListener('click', function () { setVerdict('denied'); });

  // The note saves on its own too (so a comment without a button click sticks),
  // keeping whatever Approve/Needs-work state is already showing.
  let t = null;
  note.addEventListener('input', function () {
    clearTimeout(t);
    const state = approve.classList.contains('active') ? 'approved'
                : deny.classList.contains('active') ? 'denied' : '';
    t = setTimeout(function () { save(state, note.value, 'saved ✓'); }, 600);
  });
});

// Copy-to-continue: copy the self-contained resume prompt to the clipboard.
// Falls back to selecting the textarea when the async Clipboard API is
// unavailable (http on a non-localhost host, or an older browser).
(function () {
  const btn = document.getElementById('copy-continue');
  const ta = document.getElementById('continue-prompt');
  const status = document.getElementById('copy-continue-status');
  if (!btn || !ta) return;
  function flash(msg) {
    btn.classList.add('done');
    status.textContent = msg;
    setTimeout(function () { btn.classList.remove('done'); status.textContent = ''; }, 2500);
  }
  btn.addEventListener('click', function () {
    const text = ta.value;
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text)
        .then(function () { flash('copied ✓ — paste into a fresh session'); })
        .catch(function () { fallback(); });
    } else {
      fallback();
    }
    function fallback() {
      ta.hidden = false;
      ta.style.position = 'absolute';
      ta.style.left = '-9999px';
      ta.select();
      try {
        document.execCommand('copy');
        flash('copied ✓ — paste into a fresh session');
      } catch (e) {
        ta.hidden = false;
        ta.style.position = '';
        ta.style.left = '';
        status.textContent = 'select the text below and copy it manually';
      }
      ta.hidden = true;
    }
  });
})();

// Refresh-thumbnails: regenerate the baked wave/progress PNGs server-side, then
// cache-bust every wave/progress <img> so the new pictures actually show (same
// URL would serve the browser's cached copy). WHY all images, not just the
// strip: per-wave thumbnails are baked by the same plan-waves.py run, so they
// go stale together.
(function () {
  const btn = document.getElementById('refresh-pics');
  const status = document.getElementById('refresh-pics-status');
  if (!btn) return;
  btn.addEventListener('click', function () {
    btn.disabled = true;
    btn.classList.remove('done');
    status.textContent = 'rebuilding pictures…';
    fetch('/api/refresh-pictures', { method: 'POST' })
      .then(function (res) { if (!res.ok) throw new Error('HTTP ' + res.status); })
      .then(function () {
        const bust = '?t=' + Date.now();
        document.querySelectorAll('img').forEach(function (img) {
          const src = img.getAttribute('src') || '';
          if (/\.png(\?|$)/.test(src) && !/reference\.jpg/.test(src)) {
            img.src = src.split('?')[0] + bust;
          }
        });
        btn.classList.add('done');
        status.textContent = 'updated ✓';
        setTimeout(function () {
          btn.classList.remove('done'); status.textContent = ''; btn.disabled = false;
        }, 2000);
      })
      .catch(function (e) {
        status.textContent = 'refresh failed — ' + e.message;
        btn.disabled = false;
      });
  });
})();
"""

HUB_CSS = """
 :root {
   --paper: #F6F3EC; --card: #FFFFFF; --ink: #202A36; --muted: #7A746A;
   --line: #E4DFD3; --accent: #19599C; --accent-soft: #EAF1F8;
   --apply: #D4501E; --agree: #1F7A45;
   --shadow: 0 1px 2px rgba(32,42,54,.05), 0 10px 28px rgba(32,42,54,.08);
   --serif: Charter, 'Iowan Old Style', Georgia, serif;
 }
 * { box-sizing: border-box; }
 body { font-family: 'Avenir Next', Seravek, 'Helvetica Neue', -apple-system, sans-serif;
        margin: 0; background: var(--paper); color: var(--ink);
        -webkit-font-smoothing: antialiased; }
 header { padding: 20px 24px 14px; background: var(--card);
          border-bottom: 1px solid var(--line); }
 h1 { font-family: var(--serif); font-weight: 600; font-size: 25px;
      letter-spacing: .1px; margin: 0 0 6px; }
 p { margin: 5px 0; }
 .muted { color: var(--muted); font-size: 13.5px; line-height: 1.55; }
 main { max-width: 760px; margin: 0 auto; padding: 12px 24px 32px; }
 .gate { background: var(--card); border: 1px solid var(--line); border-radius: 14px;
         padding: 18px 20px; margin: 16px 0; font-size: 15.5px;
         box-shadow: var(--shadow);
         animation: rise .45s ease both; }
 .gate:nth-child(2) { animation-delay: .08s; }
 .gate:nth-child(3) { animation-delay: .16s; }
 @keyframes rise { from { opacity: 0; transform: translateY(8px); } }
 .gate h2 { font-family: var(--serif); font-size: 19px; margin: 0 0 6px; }
 .gate.done { opacity: .65; }
 .badge { font-size: 12px; font-weight: 600; letter-spacing: .04em;
          padding: 3px 11px; border-radius: 999px;
          color: #fff; margin-left: 10px; vertical-align: 3px; }
 .badge.open { background: var(--apply); } .badge.done { background: var(--agree); }
 a.go { display: inline-flex; align-items: center; margin-top: 10px;
        font-size: 15px; font-weight: 500;
        background: var(--accent); color: #fff; text-decoration: none;
        height: 36px; padding: 0 18px; border-radius: 999px;
        transition: transform .15s ease, box-shadow .15s ease; }
 a.go:hover { transform: translateY(-1px); box-shadow: var(--shadow); }
 ul { margin: 6px 0; padding-left: 22px; }
"""

PALETTE_HTML = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Do the colours look right?</title>
<style>__CSS__
 img { max-width: 100%; display: block; border-radius: 10px; }
 button { font: inherit; font-size: 15px; font-weight: 600; color: #fff;
          display: inline-flex; align-items: center; height: 36px;
          padding: 0 18px; border-radius: 999px; border: 1px solid var(--agree);
          background: var(--agree); cursor: pointer;
          transition: transform .15s ease, box-shadow .15s ease; }
 button:hover { transform: translateY(-1px); box-shadow: var(--shadow); }
 button:disabled { opacity: .65; cursor: default; transform: none; box-shadow: none; }
 textarea { width: 100%; font: inherit; font-size: 14.5px; padding: 10px 12px;
            border-radius: 10px; border: 1px solid var(--line);
            background: var(--card); color: var(--ink); resize: vertical; }
 textarea:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
 #saved { color: var(--agree); font-size: 14px; margin-left: 10px; }
</style></head><body>
<header>
 <h1>Do the colours look right?</h1>
 <p class="muted">These are the colours we measured from your picture — each
  swatch shows one colour and how much of the picture uses it. We will only
  paint with these. <a href="/">Back to your review list</a></p>
</header>
<main>
 <div class="gate"><img src="/swatch-sheet.png" alt="the colours next to your picture"></div>
 <div class="gate" id="gatebox">
  <h2>Your verdict</h2>
  <p><button id="agree">These colours are right</button>
     <span id="saved"></span></p>
  <p class="muted">Anything off? Say it in your own words — "the dark blue is
   too dark", "there should be a gold" — it saves as you type.</p>
  <textarea id="note" rows="3" placeholder="The dark blue is too dark…">__NOTE__</textarea>
  <span id="notesaved" class="muted"></span>
 </div>
</main>
<script>
 const agreed = __AGREED__;
 const agreeBtn = document.getElementById('agree');
 if (agreed) { agreeBtn.disabled = true; agreeBtn.textContent = 'Recorded — these colours are agreed ✓'; }
 agreeBtn.addEventListener('click', async () => {
   agreeBtn.disabled = true;
   try {
     await fetch('/api/palette-agree', { method: 'POST' });
     agreeBtn.textContent = 'Recorded — these colours are agreed ✓';
     document.getElementById('saved').textContent = 'saved ✓';
   } catch (e) {
     agreeBtn.disabled = false;
     document.getElementById('saved').textContent = "couldn't save — try again";
   }
 });
 let t = null;
 document.getElementById('note').addEventListener('input', e => {
   clearTimeout(t);
   document.getElementById('notesaved').textContent = 'saving…';
   t = setTimeout(async () => {
     try {
       await fetch('/api/palette-note', { method: 'POST', body: e.target.value });
       document.getElementById('notesaved').textContent = 'saved ✓';
     } catch { document.getElementById('notesaved').textContent = "couldn't save — try again"; }
   }, 600);
 });
</script>
</body></html>"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("session_dir", type=Path)
    ap.add_argument(
        "--center",
        nargs=2,
        type=float,
        default=None,
        help="override the planner's auto-detected medallion center",
    )
    ap.add_argument(
        "--diameter",
        type=float,
        default=None,
        help="override the planner's auto-detected medallion diameter",
    )
    ap.add_argument("--port", type=int, default=8765)
    args = ap.parse_args()

    session_dir = args.session_dir.resolve()
    analysis_dir = session_dir / "input" / "reference-analysis"
    plan_dir = (analysis_dir / "wave-plan").resolve()
    session_json = session_dir / "session.json"
    note_path = analysis_dir / "palette-feedback.txt"
    tools_dir = Path(__file__).resolve().parent

    def regen() -> None:
        # Re-run the planner with the SAME center/diameter (or let it
        # auto-detect, same as the first run); it auto-loads
        # wave-plan-overrides.json from plan_dir, so owner fixes flow through
        # grouping, flower seating, validation, and every picture.
        cmd = [sys.executable, str(tools_dir / "plan-waves.py"), str(session_dir)]
        if args.center is not None:
            cmd += ["--center", str(args.center[0]), str(args.center[1])]
        if args.diameter is not None:
            cmd += ["--diameter", str(args.diameter)]
        subprocess.run(cmd, check=True)

    def rebuild_progress_strip() -> None:
        # Rebuild the "whole picture so far" strip (progress.png) from the
        # CURRENT renders: the reference first, then each passed wave's frozen
        # iteration render, left to right. WHY this lives here and not in
        # plan-waves.py: plan-waves regenerates the *reference-overlay* wave
        # pictures, but progress.png is the *build-render* filmstrip — it was a
        # hand-stitched artifact with no generator, which is exactly why it went
        # stale (last rebuilt only when someone remembered to). This makes the
        # Refresh button rebuild it deterministically from the latest renders.
        from PIL import Image  # local import: only the refresh path needs PIL

        s = session()
        passed = s.get("stage_gates", {}).get("structure", {}).get("waves_passed", {})
        # One render per distinct iteration that owns a passed wave, in build
        # order (lowest wave first); the reference leads.
        seen: set[int] = set()
        iters_in_order: list[int] = []
        for w in sorted(passed, key=lambda k: int(k)):
            it = passed[w].get("iter")
            if it is not None and it not in seen:
                seen.add(it)
                iters_in_order.append(it)

        frames: list[Image.Image] = []
        ref = session_dir / "input" / "reference.jpg"
        if ref.exists():
            frames.append(Image.open(ref).convert("RGB"))
        for it in iters_in_order:
            for name in ("render.png", "render.cairo.png"):
                rp = session_dir / "iterations" / str(it) / name
                if rp.exists():
                    frames.append(Image.open(rp).convert("RGB"))
                    break
        if not frames:
            return

        # Normalise to a common height, lay out horizontally with a thin gutter.
        H = 360
        gutter = 12
        bg = (251, 250, 247)  # matches the portal card background
        scaled = []
        for im in frames:
            w = max(1, round(im.width * H / im.height))
            scaled.append(im.resize((w, H)))
        total_w = sum(im.width for im in scaled) + gutter * (len(scaled) + 1)
        strip = Image.new("RGB", (total_w, H + 2 * gutter), bg)
        x = gutter
        for im in scaled:
            strip.paste(im, (x, gutter))
            x += im.width + gutter
        strip.save(session_dir / "progress.png")

    def session() -> dict:
        return json.loads(session_json.read_text())

    def save_session(s: dict) -> None:
        session_json.write_text(json.dumps(s, indent=2) + "\n")

    def latest_gate_sbs(wave: int) -> Path | None:
        # The newest iteration that ran a wave-diff for this wave owns the
        # gate picture (our render | reference, gold-outlined wave region).
        iters = sorted(
            (d for d in (session_dir / "iterations").iterdir() if d.name.isdigit()),
            key=lambda d: int(d.name),
            reverse=True,
        )
        for it in iters:
            p = it / "wave-diff" / f"wave-{wave:02d}" / "sbs.png"
            if p.exists():
                return p
        return None

    def wave_history(wave: int) -> list[dict]:
        # Every iteration that produced a gate picture for this wave, newest
        # first: the "how this wave evolved" timeline behind the filmstrip.
        # Each entry carries the iter number, its coverage (read from that
        # iteration's wave-diff.json), and that the sbs thumbnail exists.
        # Example: wave 1 -> [{iter:70, coverage:0.976}, {iter:69, ...}, ...]
        # spanning all 32 iterations that re-cut wave-1's crop.
        out: list[dict] = []
        for it in sorted(
            (d for d in (session_dir / "iterations").iterdir() if d.name.isdigit()),
            key=lambda d: int(d.name),
            reverse=True,
        ):
            wd = it / "wave-diff" / f"wave-{wave:02d}"
            if not (wd / "sbs.png").exists():
                continue
            cov = None
            meta = wd / "wave-diff.json"
            if meta.exists():
                try:
                    cov = json.loads(meta.read_text()).get("coverage")
                except Exception:
                    cov = None
            out.append({"iter": int(it.name), "coverage": cov})
        return out

    def history_sbs(wave: int, it: int) -> Path | None:
        # The sbs picture for ONE specific iteration of a wave (the filmstrip
        # thumbnail route), as opposed to latest_gate_sbs's newest-only pick.
        p = (session_dir / "iterations" / str(it)
             / "wave-diff" / f"wave-{wave:02d}" / "sbs.png")
        return p if p.exists() else None

    def continue_prompt_text(next_wave, next_desc: str, n_built: int, n_total: int) -> str:
        # WHY a literal heredoc and not a reference to LOOP-PROMPT.md: the owner
        # pastes this into a CLEAN session where nothing on disk has been read
        # yet. It must carry its own pointers to the durable anchors (the
        # in-session task list does not survive /clear) and the master skill,
        # plus the exact next wave, so the cold loop builds instead of idling —
        # the failure this whole button exists to prevent.
        sd = str(session_dir)
        return (
            "/loop Continue the medallion-10 stage-gated reconstruction. "
            f"BUILD the next unbuilt wave: {next_desc}. "
            f"Progress: {n_built}/{n_total} structure waves built.\n\n"
            "READ FIRST (the in-session task list does NOT survive /clear — these on-disk anchors are the memory):\n"
            "- Loop memory: /Users/omareid/.claude/projects/-Users-omareid-Workspace-git-sacred-patterns/memory/MEMORY.md\n"
            "- Master iteration skill (staged protocol; census = PRIMARY gate, eyeball = DECISIVE, do NOT tune toward iou):\n"
            "  sacred-patterns/.claude/skills/iterate-construction-hypothesis/SKILL.md\n"
            f"- Session state (waves_passed, stage_gates): {sd}/session.json\n"
            f"- Live pattern: {sd}/iterations/<latest>/pattern.bkr\n"
            "- Wave plan (this portal): http://127.0.0.1:8765/plan  ·  build view: http://127.0.0.1:8765/iterate\n\n"
            "OWNER FEEDBACK FIRST (decisive gate, every tick before building):\n"
            "  /Users/omareid/Workspace/git/qiyas/.venv/bin/python sacred-patterns/tools/wave-feedback.py \\\n"
            f"    {sd}\n"
            "  Exit 2 = a wave was denied; fix the lowest-numbered denied wave first (its note IS the fix "
            "instruction) before building the next wave. Do NOT self-clear a denial — only the owner flips it back.\n\n"
            "BUILD LOOP: build the next unbuilt wave per the wave plan, one wave per iteration, gated by:\n"
            "  1. Census-equality (PRIMARY): re-render with --emit-truth; diff gt.json (type,sides) buckets vs the "
            "pre-change render. Only the intended faces may change; zero new buckets / no spurious face-split.\n"
            "  2. Eyeball (DECISIVE, Tenet 24/27): STATE the expected visual BEFORE viewing, then build the wave "
            "side-by-side crop at matched scale vs input/reference.jpg and confirm the expected change.\n"
            "  3. iou is attribution-only — do NOT tune toward it (Tenet 7).\n"
            "After a wave passes: stamp session.json waves_passed, re-render, and the owner re-judges it in the portal. "
            "Continue until wave 22 passes (then the structure stage reaches the owner approval gate).\n\n"
            "CONSTRAINTS:\n"
            "- Node 22 for bikar render: export PATH=\"/Users/omareid/.nvm/versions/node/v22.22.3/bin:$PATH\"\n"
            "- bikar CLI: /Users/omareid/Workspace/git/bikar/packages/cli/dist/index.js render <bkr> -o <svg> "
            "--emit-truth <gt.json> --image <png> --width 1024 --height 1024\n"
            "- qiyas venv python (PIL/numpy/scipy/cairosvg): /Users/omareid/Workspace/git/qiyas/.venv/bin/python\n"
            "- qiyas detector is FROZEN — never tune a qiyas number from this loop.\n"
            "- sacred-patterns has NO active CI (pushes cheap); bikar/qiyas pushes follow Tenet 22 (batch, name CI sim)."
        )

    def iterate_html() -> str:
        # The build-progress companion to /plan: one card per wave, in build
        # order. Built waves show our render beside the reference; the next
        # wave is called out; everything else shows the plan's wave picture.
        s = session()
        passed = s.get("stage_gates", {}).get("structure", {}).get("waves_passed", {})
        plan = json.loads((plan_dir / "wave-plan.json").read_text())
        waves = sorted(plan["waves"], key=lambda w: w["wave"])
        next_wave = next((w["wave"] for w in waves if str(w["wave"]) not in passed), None)
        n_built = sum(1 for w in waves if str(w["wave"]) in passed)

        # The "Copy to continue" prompt: a self-contained /loop instruction the
        # owner can paste into a fresh session if the build ever stalls. It must
        # survive /clear, so it names the on-disk anchors (the in-session task
        # list does NOT survive) and the master iteration skill, and pins the
        # exact next wave so the cold session resumes building, not idling.
        next_spec = next((w for w in waves if w["wave"] == next_wave), None)
        if next_wave is not None and next_spec is not None:
            nc = str(next_spec.get("color", "")).replace("_", " ")
            ncount = next_spec.get("real_shape_count", next_spec.get("shape_count", "?"))
            next_desc = f"wave {next_wave} ({ncount} {nc} shapes {next_spec.get('where', '')})".strip()
        else:
            next_desc = "the structure stage is fully built — next is the owner approval gate"
        continue_prompt = continue_prompt_text(next_wave, next_desc, n_built, len(waves))

        cards = []
        for w in waves:
            n = w["wave"]
            colour = str(w.get("color", "")).replace("_", " ")
            count = w.get("real_shape_count", w.get("shape_count", "?"))
            what = f"{count} {colour} shape{'s' if count != 1 else ''} {w.get('where', '')}"
            gate = passed.get(str(n))
            if gate:
                sbs = latest_gate_sbs(n)
                img = (
                    f"<img src='/gate/{n}/sbs.png' alt='wave {n}: ours beside yours'>"
                    "<p class='muted caption'>Ours on the left, your picture on the "
                    "right — this wave's shapes are outlined in gold.</p>"
                    if sbs
                    else ""
                )
                pct = round(gate.get("coverage", 0) * 100)
                # owner_verdict is `None` until the owner judges the wave (the
                # stamp writes it as an explicit null), so a bare .get default of
                # {} is not enough — coerce the null to {} before reading .state.
                verdict = gate.get("owner_verdict") or {}
                vstate = verdict.get("state", "")  # "" | "approved" | "denied"
                vnote = verdict.get("note", "")
                # The owner's per-wave call lives right on the card: Approve /
                # Needs work, plus a comment that (on Needs-work) becomes the
                # fix instruction the loop picks up. data-wave drives the JS.
                badge = "<span class='badge done'>built ✓</span>"
                if vstate == "approved":
                    badge += "<span class='badge ok'>you approved ✓</span>"
                elif vstate == "denied":
                    badge += "<span class='badge no'>needs work ✗</span>"
                # Filmstrip: every past iteration of this wave, newest first.
                hist = wave_history(n)
                frame_parts = []
                for h in hist:
                    it_n = h["iter"]
                    pct_txt = ("" if h["coverage"] is None
                               else f", {round(h['coverage'] * 100)}%")
                    cap = ("" if h["coverage"] is None
                           else f" · {round(h['coverage'] * 100)}%")
                    # No loading='lazy' here: these frames live inside a
                    # collapsed <details>, and a lazy <img> in a display:none
                    # container never enters the viewport, so it never loads —
                    # it renders as a broken-image icon the moment the details
                    # is opened. Eager-load so every frame is ready on expand.
                    frame_parts.append(
                        f"<a class='frame' href='/gate/{n}/{it_n}/sbs.png' "
                        f"target='_blank' title='step {it_n}{pct_txt}'>"
                        f"<img src='/gate/{n}/{it_n}/sbs.png' "
                        f"alt='wave {n} at step {it_n}'>"
                        f"<span class='muted'>{it_n}{cap}</span></a>"
                    )
                frames = "".join(frame_parts)
                history = (
                    f"<details class='history'><summary class='muted'>"
                    f"Show history ({len(hist)} step{'s' if len(hist) != 1 else ''})</summary>"
                    f"<div class='filmstrip'>{frames}</div></details>"
                    if hist else ""
                )
                panel = (
                    f"<div class='verdict' data-wave='{n}'>"
                    f"<div class='vbtns'>"
                    f"<button class='approve'>This wave looks right</button>"
                    f"<button class='deny'>Needs work</button>"
                    f"</div>"
                    f"<div class='vsaved muted'></div>"
                    "<p class='muted'>Anything off? Say it in your own words — "
                    "\"the star points are too thin\", \"this should be gold\". On "
                    "<b>Needs work</b> this is the fix we'll make next.</p>"
                    f"<textarea class='vnote' rows='3' placeholder='What should change?'>"
                    f"{html.escape(vnote)}</textarea></div>"
                )
                # Two-column card: the gate picture + its history filmstrip on
                # the left, the owner's verdict/feedback panel on the right, so
                # the reviewer looks at the wave and votes on it side by side
                # (the panel doesn't push the picture off-screen).
                cards.append(
                    f"<div class='gate built' data-wave-card='{n}'><h2>Wave {n} — "
                    f"{html.escape(what)}{badge}</h2>"
                    f"<p class='muted'>Built in step {gate.get('iter', '?')}; our paint "
                    f"covers {pct}% of these shapes.</p>"
                    f"<div class='gate-row'>"
                    f"<div class='gate-main'>{img}{history}</div>"
                    f"<div class='gate-side'>{panel}</div>"
                    f"</div></div>"
                )
            elif n == next_wave:
                # The Copy-to-continue action lives ON the building-now card
                # (owner, 2026-06-14: "copy button should be next to wave that's
                # processing, not up top") so resuming a stalled build is right
                # where the eye already is — on the wave in progress.
                cards.append(
                    f"<div class='gate' data-wave-card='{n}'><h2>Wave {n} — {html.escape(what)}"
                    "<span class='badge open'>building now</span></h2>"
                    "<p class='muted'>This is the wave we're working on — it's "
                    "highlighted below on your picture.</p>"
                    f"<img src='/wave-{n}.png' alt='wave {n} on your picture'>"
                    "<div class='continue'>"
                    "<button id='copy-continue' type='button'>📋 Copy prompt to continue building</button>"
                    "<span id='copy-continue-status' class='muted'></span>"
                    "<p class='muted'>If the build ever stops, paste this into a fresh "
                    "session to resume from this wave.</p>"
                    f"<textarea id='continue-prompt' hidden>{html.escape(continue_prompt)}</textarea>"
                    "</div></div>"
                )
            else:
                cards.append(
                    f"<div class='gate todo'><h2>Wave {n} — {html.escape(what)}"
                    "<span class='badge todo'>coming up</span></h2>"
                    f"<details><summary class='muted'>See it on your picture</summary>"
                    f"<img loading='lazy' src='/wave-{n}.png' alt='wave {n} on your picture'></details></div>"
                )

        # Progress as a row of stacked squares, one per wave (owner, 2026-06-14:
        # "green and white squares ... which wave we reached, what's left").
        # Green = passed, white = remaining; the next-to-build wave gets a ring
        # so the eye lands on where the build is. Each square is titled with its
        # wave number + state so hovering reads as a plain-language tooltip.
        sq = []
        for w in waves:
            n = w["wave"]
            done = str(n) in passed
            cls = "sq done" if done else "sq todo"
            if n == next_wave:
                cls += " here"
            state = "done" if done else ("building now" if n == next_wave else "to do")
            sq.append(f"<span class='{cls}' title='Wave {n} — {state}'></span>")
        squares = (
            "<div class='squares' role='img' "
            f"aria-label='{n_built} of {len(waves)} waves done'>"
            + "".join(sq)
            + "</div>"
        )
        bar = f"{(n_built / len(waves) * 100):.0f}%" if waves else "0%"
        # A pointer to the per-wave page (owner, 2026-06-15: the picker became a
        # plain "waves page" with all views shown at once — /waves).
        waves_link = (
            "<div class='gate'><h2>The waves, one by one"
            "<span class='badge done'>live</span></h2>"
            "<p class='muted'>Every wave on one page — your photo zoomed to its "
            "shapes, our build, just that wave's shapes, and the recipe change. "
            "<a href='/waves'>Open the waves page</a>.</p></div>"
        )
        progress_img = (
            "<div class='gate'><h2>The whole picture so far "
            "<button id='refresh-pics' type='button' class='refresh'>↻ Refresh thumbnails</button>"
            "<span id='refresh-pics-status' class='muted'></span></h2>"
            "<p class='muted'>Your picture on the left, our latest full render "
            "on the right. If it looks out of date, click Refresh.</p>"
            "<img id='progress-strip' src='/progress.png' alt='progress so far'></div>"
            if (session_dir / "progress.png").exists()
            else ""
        )
        extra_css = """
 img { max-width: 100%; display: block; border-radius: 10px; margin-top: 8px; }
 .caption { margin-top: 6px; }
 .badge.todo { background: #B7AE9D; }
 .gate.todo { opacity: .72; }
 details summary { cursor: pointer; }
 .bar { height: 10px; border-radius: 999px; background: var(--line); overflow: hidden; margin-top: 8px; }
 .bar > div { height: 100%; background: var(--agree); border-radius: 999px;
              transition: width .6s ease; }
 /* Stacked-squares progress: one square per wave, green=done / white=left,
    a ring on the wave currently building. */
 .squares { display: flex; flex-wrap: wrap; gap: 5px; margin: 10px 0 4px; }
 .squares .sq { width: 22px; height: 22px; border-radius: 5px;
                border: 1px solid var(--line); box-sizing: border-box; }
 .squares .sq.done { background: #2E7D5B; border-color: #2E7D5B; }
 .squares .sq.todo { background: #fff; }
 .squares .sq.here { outline: 2px solid #B8860B; outline-offset: 1px; }
 .badge.ok { background: #2E7D5B; }
 .badge.no { background: #B23A48; }
 /* The built-wave cards are two columns (picture | feedback), so the
    iterate page needs more room than the 760px reading width the shared hub
    CSS sets. Widen main here only; / and /plan keep the narrow width. */
 main { max-width: 1000px; }
 .gate.built { max-width: 1000px; }
 .gate-row { display: flex; gap: 18px; align-items: flex-start; margin-top: 8px; }
 .gate-main { flex: 1 1 60%; min-width: 0; }
 .gate-side { flex: 1 1 40%; min-width: 280px; }
 .gate-side .verdict { margin-top: 0; }
 @media (max-width: 760px) { .gate-row { flex-direction: column; }
                             .gate-side { min-width: 0; width: 100%; } }
 .verdict { margin-top: 12px; padding: 14px 16px; border: 1px solid var(--line);
            border-radius: 12px; background: #FBFAF7; }
 /* Buttons share one wrapping row; the save-status sits on its own line below
    so a long message ("couldn't save — try again") never crams between the two
    buttons or pushes them apart. */
 .vbtns { display: flex; flex-wrap: wrap; gap: 8px; }
 .verdict button { margin: 0; border: 1px solid var(--line); background: #fff;
                   border-radius: 8px; padding: 8px 14px; font: inherit;
                   cursor: pointer; transition: background .15s, color .15s; }
 .verdict button.approve.active { background: #2E7D5B; color: #fff; border-color: #2E7D5B; }
 .verdict button.deny.active { background: #B23A48; color: #fff; border-color: #B23A48; }
 .vsaved { display: block; min-height: 16px; margin-top: 8px; font-size: 13px; }
 .vsaved.ok { color: #2E7D5B; } .vsaved.err { color: #B23A48; }
 .vsaved.wait { color: #B8860B; }
 .verdict textarea { width: 100%; margin-top: 4px; box-sizing: border-box;
                     border: 1px solid var(--line); border-radius: 8px; padding: 8px;
                     font: inherit; resize: vertical; }
 .history { margin-top: 10px; }
 .filmstrip { display: flex; gap: 10px; overflow-x: auto; padding: 8px 2px; }
 .filmstrip .frame { flex: 0 0 auto; width: 150px; text-align: center;
                     text-decoration: none; }
 .filmstrip .frame img { width: 150px; margin: 0; border: 1px solid var(--line); }
 .filmstrip .frame span { display: block; font-size: 12px; margin-top: 2px; }
 /* Copy-to-continue: a prominent action so the owner can resume a stalled
    build from a clean session without hunting for the loop prompt. */
 .continue { margin-top: 14px; padding: 12px 14px; border: 1px solid var(--line);
             border-radius: 12px; background: #FBFAF7; }
 #copy-continue { border: 1px solid var(--agree); background: var(--agree);
                  color: #fff; border-radius: 8px; padding: 9px 16px;
                  font: inherit; cursor: pointer; transition: opacity .15s; }
 #copy-continue:hover { opacity: .9; }
 #copy-continue.done { background: #2E7D5B; border-color: #2E7D5B; }
 #copy-continue-status { margin-left: 10px; font-size: 13px; }
 .continue p { margin: 8px 0 0; }
 /* Refresh-thumbnails: a small inline action in the progress-strip heading so
    the owner can rebuild stale baked PNGs on demand without a server restart. */
 button.refresh { font: inherit; font-size: 14px; vertical-align: middle;
                  margin-left: 12px; border: 1px solid var(--line); background: #fff;
                  border-radius: 8px; padding: 5px 12px; cursor: pointer;
                  transition: background .15s; }
 button.refresh:hover { background: #F2EFE9; }
 button.refresh:disabled { opacity: .55; cursor: default; }
 button.refresh.done { background: #2E7D5B; color: #fff; border-color: #2E7D5B; }
 #refresh-pics-status { margin-left: 10px; font-size: 13px; }
"""
        return (
            "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            f"<title>Watching it get built</title><style>{HUB_CSS}{extra_css}</style></head><body>"
            "<header><h1>Watching it get built</h1>"
            f"<p>We rebuild your picture wave by wave, from the centre outward. "
            f"<b>{n_built} of {len(waves)} waves are built.</b></p>"
            f"{squares}"
            "<p class='muted'><a href='/'>Back to your review list</a> · "
            "<a href='/plan'>See the building plan</a></p>"
            "</header>"
            f"<main>{progress_img}{waves_link}{''.join(cards)}</main>"
            f"<script>{ITERATE_JS}</script></body></html>"
        )

    def best_iter() -> int | None:
        # The frozen current-best is the iteration that passed the highest
        # wave — its render is what /slides closes on.
        s = session()
        passed = s.get("stage_gates", {}).get("structure", {}).get("waves_passed", {})
        iters = [g.get("iter") for g in passed.values() if g.get("iter")]
        return max(iters) if iters else None

    def png_dims(p: Path) -> tuple[int, int] | None:
        # PNG IHDR: width/height are big-endian uint32 at bytes 16..24.
        with open(p, "rb") as f:
            head = f.read(24)
        if head[:8] != b"\x89PNG\r\n\x1a\n":
            return None
        return (
            int.from_bytes(head[16:20], "big"),
            int.from_bytes(head[20:24], "big"),
        )

    def bkr_text(it: int | None) -> str:
        if it is None:
            return ""
        p = session_dir / "iterations" / str(it) / "pattern.bkr"
        return p.read_text() if p.exists() else ""

    def diff_panes(before: str, after: str) -> tuple[str, str]:
        # PR-style side-by-side: the before recipe with removed lines red,
        # the after recipe with added lines green; long unchanged runs
        # collapse to a count so the change is what fills the frame.
        import difflib

        al, bl = before.splitlines(), after.splitlines()
        sm = difflib.SequenceMatcher(None, al, bl, autojunk=False)
        left: list[str] = []
        right: list[str] = []
        CTX = 3
        for tag, i1, i2, j1, j2 in sm.get_opcodes():
            if tag == "equal":
                run = al[i1:i2]
                if len(run) > 2 * CTX + 2:
                    kept = run[:CTX]
                    skip = f"<span class='skip'>··· {len(run) - 2 * CTX} unchanged lines ···</span>"
                    tail = run[-CTX:]
                    block = [html.escape(x) for x in kept] + [skip] + [html.escape(x) for x in tail]
                    left += block
                    right += block
                else:
                    left += [html.escape(x) for x in run]
                    right += [html.escape(x) for x in run]
                continue
            if tag in ("delete", "replace"):
                left += [f"<span class='del'>{html.escape(x) or ' '}</span>" for x in al[i1:i2]]
            if tag in ("insert", "replace"):
                right += [f"<span class='ins'>{html.escape(x) or ' '}</span>" for x in bl[j1:j2]]
        return "\n".join(left), "\n".join(right)

    def slides_html() -> str:
        # A reveal.js deck telling the build story: title (progress strip),
        # then per PASSED wave a slide pair — the gate side-by-side, then the
        # recipe (DSL) diff that built it — closing on current best beside
        # the reference. Reads session.json and wave-plan.json per request,
        # same as /iterate — passing a new wave updates the deck with zero
        # regeneration.
        s = session()
        passed = s.get("stage_gates", {}).get("structure", {}).get("waves_passed", {})
        plan = json.loads((plan_dir / "wave-plan.json").read_text())
        waves = sorted(plan["waves"], key=lambda w: w["wave"])
        n_built = sum(1 for w in waves if str(w["wave"]) in passed)

        # Every slide's picture sits in ONE fixed frame sized by the biggest
        # gate image (owner, 2026-06-11: "image size should be consistent
        # across slides") — inner waves' tight crops upscale to fill it,
        # which doubles as the zoom their small shapes need.
        dims = [
            d
            for w in waves
            if str(w["wave"]) in passed and (p := latest_gate_sbs(w["wave"]))
            if (d := png_dims(p))
        ]
        box_w = max((d[0] for d in dims), default=1100)
        box_h = max((d[1] for d in dims), default=550)

        slides = [
            "<section><h1>Watching it get built</h1>"
            "<img class='shot' src='/progress.png' alt='progress so far'>"
            f"<p class='cap'><b>{n_built} of {len(waves)} waves built</b> — "
            "your picture first, then each building step. "
            "Tap, click, or use the arrow keys to move forward.</p>"
            "</section>"
        ]
        prev_iter: int | None = None
        for w in waves:
            n = w["wave"]
            gate = passed.get(str(n))
            if not gate or latest_gate_sbs(n) is None:
                continue
            colour = str(w.get("color", "")).replace("_", " ")
            count = w.get("real_shape_count", w.get("shape_count", "?"))
            what = f"{count} {colour} shape{'s' if count != 1 else ''} {w.get('where', '')}"
            pct = round(gate.get("coverage", 0) * 100)
            slides.append(
                f"<section><h2>Wave {n} <span class='what'>— {html.escape(what)}</span></h2>"
                f"<img class='shot' src='/gate/{n}/sbs.png' alt='wave {n}: ours beside yours'>"
                f"<p class='cap'>Built in step {gate.get('iter', '?')}; our paint covers "
                f"{pct}% of these shapes. Ours on the left, your picture on the right — "
                "this wave's shapes are outlined in gold.</p></section>"
            )
            it = gate.get("iter")
            after = bkr_text(it)
            if after:
                lpane, rpane = diff_panes(bkr_text(prev_iter), after)
                slides.append(
                    f"<section><h2>Wave {n} <span class='what'>— the recipe change</span></h2>"
                    f"<div class='pair codepair'><pre>{lpane}</pre><pre>{rpane}</pre></div>"
                    "<p class='cap'>Every wave is drawn from a written recipe. Left: the recipe "
                    "before this wave (<span class='del'>red = taken out</span>). Right: after "
                    "(<span class='ins'>green = added</span>). Unchanged parts are folded away.</p>"
                    "</section>"
                )
            prev_iter = it or prev_iter
        if best_iter() is not None:
            slides.append(
                "<section><h2>Where we are now</h2>"
                "<div class='pair'>"
                "<figure><img src='/current-best.png' alt='ours so far'>"
                "<figcaption>Ours so far</figcaption></figure>"
                "<figure><img src='/reference.jpg' alt='your picture'>"
                "<figcaption>Your picture</figcaption></figure></div>"
                f"<p class='cap'>{n_built} of {len(waves)} waves built — "
                "the rest are on their way, working outward.</p></section>"
            )
        # Fixed slide geometry: a constant header zone, then the image frame,
        # then the caption — so the title never moves between slides and only
        # the picture content changes (owner, 2026-06-11).
        head_h = 84
        css = f"""
 .shot {{ width: {box_w}px; height: {box_h}px; object-fit: contain;
   display: block; margin: 0 auto; }}
 .pair {{ width: {box_w}px; height: {box_h}px; margin: 0 auto;
   display: flex; gap: 24px; justify-content: center; }}
 .reveal h1, .reveal h2 {{ height: {head_h}px; margin: 0 0 12px;
   display: flex; align-items: center; justify-content: center; gap: .35ch; }}
 .codepair pre {{ flex: 1; min-width: 0; height: {box_h}px; overflow: auto;
   box-sizing: border-box;
   margin: 0; text-align: left; font-size: 13px; line-height: 1.45;
   font-family: ui-monospace, 'SF Mono', Menlo, monospace;
   background: #FFFFFF; border-radius: 10px; padding: 12px 16px;
   box-shadow: 0 1px 2px rgba(32,42,54,.05), 0 10px 28px rgba(32,42,54,.08);
   color: #202A36; }}
""" + """
 .del { background: #FBE3E3; border-radius: 3px; }
 .ins { background: #DFF2E3; border-radius: 3px; }
 .skip { color: #B7AE9D; }
 .reveal { font-family: 'Avenir Next', Seravek, 'Helvetica Neue', -apple-system, sans-serif; }
 .reveal h1, .reveal h2 { font-family: Charter, 'Iowan Old Style', Georgia, serif;
   color: #202A36; text-transform: none; letter-spacing: .1px; }
 .reveal h1 { font-size: 1.7em; } .reveal h2 { font-size: 1.3em; }
 .reveal .what { color: #7A746A; font-weight: 400; }
 .reveal p { color: #202A36; }
 .reveal .cap { color: #7A746A; font-size: .52em; line-height: 1.5; margin: 12px 0 0; }
 .reveal img { border-radius: 10px; box-shadow: 0 1px 2px rgba(32,42,54,.05),
   0 10px 28px rgba(32,42,54,.08); }
 .pair figure { margin: 0; flex: 1; min-width: 0; height: 100%;
   display: flex; flex-direction: column; }
 .pair img { flex: 1; min-height: 0; width: 100%; object-fit: contain; }
 .pair figcaption { color: #7A746A; font-size: .5em; margin-top: 8px; }
 .home { position: fixed; top: 14px; left: 18px; z-index: 50; font-size: 14px;
   font-family: 'Avenir Next', sans-serif; color: #19599C; text-decoration: none; }
"""
        return (
            "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            "<title>The build, slide by slide</title>"
            "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/reveal.css'>"
            f"<style>body {{ background: #F6F3EC; }}{css}</style></head><body>"
            "<a class='home' href='/'>← Back to your review list</a>"
            f"<div class='reveal'><div class='slides'>{''.join(slides)}</div></div>"
            "<script src='https://cdn.jsdelivr.net/npm/reveal.js@5.1.0/dist/reveal.js'></script>"
            # Fixed canvas sized to the frame + header + caption; center:false
            # keeps every slide top-anchored so the title never moves.
            f"<script>Reveal.initialize({{ hash: true, transition: 'fade',"
            f" controlsTutorial: true, slideNumber: 'c/t', center: false,"
            f" width: {box_w + 60}, height: {head_h + box_h + 170}, margin: 0.02 }});</script>"
            "</body></html>"
        )

    # The pictures we show for EVERY wave — no picker (owner, 2026-06-15: "I dont
    # want a view picker per wave ... I want to see all three for a card"). The
    # DEFAULT/primary tile is a tight CROP of the reference photo focused on this
    # wave's shapes (owner: "a cropped version of Your original photo's steps
    # focused on the shapes being recreated"); the others sit beside it. The
    # code-diff tile is built separately (it needs the recipe text, not a URL).
    WAVE_VIEWS = [
        ("crop", "Your photo, zoomed to this wave",
         "Your original reference photo, zoomed in on just the shapes this wave "
         "rebuilds — each one ringed in orange.",
         lambda n: f"/wave-ghosts/wave-{n}-crop.png"),
        ("ours", "Our build",
         "The whole picture faded to grey with only this ring lit up in colour, "
         "built from <em>our</em> drawing.",
         lambda n: f"/wave-ghosts/wave-{n}.png"),
        ("iso", "Just this wave's shapes",
         "Only the shapes this wave adds, on a clean white page — nothing else.",
         lambda n: f"/wave-ghosts/wave-{n}-iso.png"),
    ]

    def wave_view_choices() -> dict:
        # Legacy: the owner's old per-wave view picks. The picker is gone
        # (2026-06-15) but the /iterate roll-up + saved choices are read
        # elsewhere, so keep the accessor returning {} when unset.
        return (
            session().get("stage_gates", {}).get("structure", {})
            .get("wave_view_choices", {})
        )

    def wave_iters_in_order(passed: dict, waves: list) -> dict:
        # wave_number -> the iteration that built it, for the waves that passed,
        # in build order. Used to diff each wave's recipe against the previous
        # built wave's recipe (the code-diff tile).
        out: dict[int, int] = {}
        for w in sorted(waves, key=lambda w: w["wave"]):
            g = passed.get(str(w["wave"]))
            if g and isinstance(g.get("iter"), int):
                out[w["wave"]] = g["iter"]
        return out

    def waves_html() -> str:
        # The "waves page" (owner, 2026-06-15: "rather a waves page with all
        # these views per wave ... and even a code diff view"). One card per
        # wave; every card shows ALL views at once — no picker. The big primary
        # tile is the zoomed reference crop; beside it our build + just-this-wave;
        # below, the recipe (.bkr) diff that built the wave. Grandma-plain
        # language, no jargon (Tenet 27).
        s = session()
        passed = s.get("stage_gates", {}).get("structure", {}).get("waves_passed", {})
        plan = json.loads((plan_dir / "wave-plan.json").read_text())
        waves = sorted(plan["waves"], key=lambda w: w["wave"])
        built_iters = wave_iters_in_order(passed, waves)

        cards = []
        prev_iter: int | None = None
        for w in waves:
            n = w["wave"]
            colour = str(w.get("color", "")).replace("_", " ")
            count = w.get("real_shape_count", w.get("shape_count", "?"))
            what = f"{count} {colour} shape{'s' if count != 1 else ''} {w.get('where', '')}".strip()
            built = str(n) in passed

            # All three views render at the SAME size in one row (owner,
            # 2026-06-15: "all three wave cards should be same size"). The crop
            # keeps an accent border so the eye knows it's the reference, but it
            # is no longer oversized. Each tile gets an "expand" button that
            # opens it full-screen in a lightbox.
            tiles = []
            for idx, (key, title, blurb, url) in enumerate(WAVE_VIEWS):
                cls = "view primary" if idx == 0 else "view"
                src = url(n)
                tiles.append(
                    f"<figure class='{cls}'>"
                    f"<div class='imgwrap'>"
                    f"<img loading='lazy' src='{src}' alt='wave {n}: {title}'>"
                    f"<button class='expand' type='button' "
                    f"data-full='{src}' data-label='{html.escape(title)}' "
                    f"title='View full screen' aria-label='View full screen'>⤢</button>"
                    f"</div>"
                    f"<figcaption><b>{title}</b>"
                    f"<span class='vblurb muted'>{blurb}</span></figcaption></figure>"
                )

            # Code-diff tile: the recipe change that built this wave, vs. the
            # previous built wave. Only meaningful for built waves (an unbuilt
            # wave has no recipe yet); folds away unchanged lines.
            it = built_iters.get(n)
            diff_tile = ""
            if it is not None:
                lpane, rpane = diff_panes(bkr_text(prev_iter), bkr_text(it))
                diff_tile = (
                    "<details class='codediff'><summary>Show the recipe change "
                    "(the lines we added to draw this wave)</summary>"
                    f"<div class='codepair'><pre>{lpane}</pre><pre>{rpane}</pre></div>"
                    "<p class='muted'>Left: the recipe before this wave "
                    "(<span class='del'>red = taken out</span>). Right: after "
                    "(<span class='ins'>green = added</span>).</p></details>"
                )
                prev_iter = it

            status = ("<span class='badge done'>built ✓</span>" if built
                      else "<span class='badge todo'>coming up</span>")
            cards.append(
                f"<div class='gate' id='w{n}' data-wave-card='{n}'>"
                f"<h2>Wave {n} — {html.escape(what)}{status}</h2>"
                f"<div class='wave-views'>{''.join(tiles)}</div>"
                f"{diff_tile}</div>"
            )

        n_built = len(passed)
        head = (
            f"{n_built} of {len(waves)} waves are built. Each card shows your "
            "photo zoomed to that wave's shapes, our build of them, just that "
            "wave's shapes on white, and the recipe lines that drew them."
        )
        extra_css = """
 /* All three views are equal-size cells in one responsive grid (owner:
    "all three wave cards should be same size"). */
 .wave-views { display: grid; gap: 14px; margin-top: 10px; align-items: start;
               grid-template-columns: repeat(3, minmax(0, 1fr)); }
 @media (max-width: 760px) { .wave-views { grid-template-columns: 1fr; } }
 .view { margin: 0; border: 1px solid var(--line); border-radius: 12px;
         padding: 8px; background: #fff; box-sizing: border-box; }
 .view.primary { border-width: 2px; border-color: var(--accent); }
 .imgwrap { position: relative; }
 /* Square the image cell so every tile is identical regardless of the source
    aspect ratio; the image fills it (object-fit: contain keeps it un-cropped). */
 .view img { width: 100%; aspect-ratio: 1 / 1; object-fit: contain;
             border-radius: 8px; display: block; background: #fff; }
 .view .expand { position: absolute; top: 8px; right: 8px; width: 34px;
                 height: 34px; border: none; border-radius: 8px; cursor: pointer;
                 background: rgba(17,24,39,.62); color: #fff; font-size: 18px;
                 line-height: 1; display: grid; place-items: center;
                 box-shadow: 0 1px 4px rgba(0,0,0,.25); }
 .view .expand:hover { background: rgba(17,24,39,.85); }
 /* Full-screen lightbox: click an expand button to fill the screen. */
 #lightbox { position: fixed; inset: 0; background: rgba(17,24,39,.92);
             display: none; place-items: center; z-index: 50; padding: 24px; }
 #lightbox.open { display: grid; }
 #lightbox figure { margin: 0; max-width: 96vw; max-height: 92vh;
                    display: grid; gap: 10px; justify-items: center; }
 #lightbox img { max-width: 96vw; max-height: 84vh; object-fit: contain;
                 border-radius: 10px; background: #fff; }
 #lightbox figcaption { color: #fff; font-size: 16px; }
 #lightbox .close { position: fixed; top: 18px; right: 22px; width: 44px;
                    height: 44px; border: none; border-radius: 10px;
                    background: rgba(255,255,255,.16); color: #fff;
                    font-size: 26px; cursor: pointer; line-height: 1; }
 .view figcaption { display: block; margin-top: 6px; }
 .view figcaption b { display: block; }
 .vblurb { display: block; font-size: 12.5px; margin: 4px 0 2px; }
 .badge.todo { background: #B7AE9D; }
 /* Code-diff tile: a foldaway PR-style two-pane recipe diff. */
 .codediff { margin-top: 12px; }
 .codediff summary { cursor: pointer; font-size: 14px; color: var(--accent); }
 .codediff .codepair { display: flex; gap: 12px; margin-top: 8px; }
 .codediff pre { flex: 1; min-width: 0; max-height: 360px; overflow: auto;
                 margin: 0; font-size: 12px; line-height: 1.4;
                 font-family: ui-monospace, 'SF Mono', Menlo, monospace;
                 background: #fff; border: 1px solid var(--line);
                 border-radius: 10px; padding: 10px 12px; }
 .del { background: #FBE3E3; border-radius: 3px; }
 .ins { background: #DFF2E3; border-radius: 3px; }
 .skip { color: #B7AE9D; }
 main { max-width: 1100px; }
"""
        return (
            "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            "<title>The waves, one by one</title>"
            f"<style>{HUB_CSS}{extra_css}</style></head><body>"
            "<header><h1>The waves, one by one</h1>"
            f"<p>{head}</p>"
            "<p class='muted'><a href='/'>Back to your review list</a> · "
            "<a href='/iterate'>Watch the build</a> · "
            "<a href='/inspect'>Tap a shape to find its wave</a></p></header>"
            f"<main>{''.join(cards)}</main>"
            # Full-screen lightbox + the expand-button wiring (Tenet 27: one tap,
            # no jargon — the ⤢ button on any tile fills the screen; click the
            # backdrop, the ✕, or press Esc to close).
            "<div id='lightbox' role='dialog' aria-modal='true'>"
            "<button class='close' type='button' aria-label='Close'>✕</button>"
            "<figure><img alt=''><figcaption></figcaption></figure></div>"
            "<script>(function(){"
            "var lb=document.getElementById('lightbox');"
            "var img=lb.querySelector('img');var cap=lb.querySelector('figcaption');"
            "function open(src,label){img.src=src;img.alt=label;cap.textContent=label;"
            "lb.classList.add('open');}"
            "function close(){lb.classList.remove('open');img.src='';}"
            "document.querySelectorAll('.expand').forEach(function(b){"
            "b.addEventListener('click',function(){"
            "open(b.getAttribute('data-full'),b.getAttribute('data-label'));});});"
            "lb.addEventListener('click',function(e){"
            "if(e.target===lb||e.target.classList.contains('close'))close();});"
            "document.addEventListener('keydown',function(e){"
            "if(e.key==='Escape')close();});"
            "})();</script>"
            "</body></html>"
        )

    def inspect_html() -> str:
        # The shape→wave inspector (owner, 2026-06-15: "a separate component
        # that allows me to see the original and final shape side by side and
        # press any sub shape of either and it tells me what wave that shape is
        # handled / introduced"). LEFT = the reference photo with a clickable
        # hotspot per wave-plan shape (each already carries its wave). RIGHT =
        # our final render; its per-shape→wave map needs the matcher fix
        # (task #26), so for now it shows the build with a plain "coming soon"
        # note rather than a wrong answer. Grandma-plain, no jargon (Tenet 27).
        s = session()
        plan = json.loads((plan_dir / "wave-plan.json").read_text())
        waves = sorted(plan["waves"], key=lambda w: w["wave"])
        ref = session_dir / "input" / "reference.jpg"
        # reference.jpg — read its size via PIL once (cheap, one image).
        try:
            from PIL import Image
            with Image.open(ref) as im:
                ref_w, ref_h = im.size
        except Exception:
            ref_w, ref_h = (753, 722)

        # One hotspot per shape: a transparent circle at the shape's photo
        # coords, sized to the shape, tagged with its wave + a plain label. The
        # SVG sits over the photo via a shared viewBox so a click maps straight
        # to the shape under the cursor.
        import math as _math
        spots = []
        for w in waves:
            n = w["wave"]
            colour = str(w.get("color", "")).replace("_", " ")
            for sh in w.get("shapes", []):
                r = max(_math.sqrt(max(sh.get("area_px", 0), 1)) / 2.0, 5)
                label = f"Wave {n} — {colour} shape"
                spots.append(
                    f"<circle cx='{sh['x']:.1f}' cy='{sh['y']:.1f}' r='{r:.1f}' "
                    f"class='spot' data-wave='{n}' "
                    f"data-label='{html.escape(label)}'></circle>"
                )
        overlay = (
            f"<svg class='spots' viewBox='0 0 {ref_w} {ref_h}' "
            f"preserveAspectRatio='xMidYMid meet'>{''.join(spots)}</svg>"
        )

        best = best_iter()
        right_img = (
            f"<img src='/current-best.png' alt='our finished drawing'>"
            if best is not None else "<p class='muted'>No build yet.</p>"
        )

        extra_css = """
 main { max-width: 1100px; }
 .panes { display: flex; gap: 18px; flex-wrap: wrap; }
 .pane { flex: 1 1 380px; min-width: 300px; }
 .stage { position: relative; line-height: 0; border: 1px solid var(--line);
          border-radius: 12px; overflow: hidden; background: #fff; }
 .stage img { width: 100%; display: block; }
 svg.spots { position: absolute; inset: 0; width: 100%; height: 100%; }
 .spot { fill: transparent; stroke: transparent; cursor: pointer;
         transition: fill .12s, stroke .12s; }
 .spot:hover { fill: rgba(227,78,16,.28); stroke: #E34E10; stroke-width: 2; }
 .spot.lit { fill: rgba(227,78,16,.45); stroke: #E34E10; stroke-width: 2.5; }
 .readout { margin-top: 12px; padding: 14px 16px; border: 1px solid var(--line);
            border-radius: 12px; background: #FBFAF7; font-size: 16px;
            min-height: 52px; display: flex; align-items: center; }
 .readout b { color: var(--accent); }
 .soon { margin-top: 8px; font-size: 13.5px; }
"""
        script = """
<script>
(function () {
  var read = document.getElementById('readout');
  document.querySelectorAll('.spot').forEach(function (c) {
    c.addEventListener('click', function () {
      document.querySelectorAll('.spot.lit').forEach(function (o) { o.classList.remove('lit'); });
      // Light every shape from the same wave, so a click shows the whole ring.
      var wv = c.getAttribute('data-wave');
      document.querySelectorAll(".spot[data-wave='" + wv + "']").forEach(function (o) { o.classList.add('lit'); });
      read.innerHTML = 'This shape is built in <b>Wave ' + wv + '</b> — ' +
        c.getAttribute('data-label').replace(/^Wave \\d+ — /, '') + '. ' +
        'Every shape we just lit up is built in the same wave.';
    });
  });
})();
</script>
"""
        return (
            "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            "<title>Tap a shape to find its wave</title>"
            f"<style>{HUB_CSS}{extra_css}</style></head><body>"
            "<header><h1>Tap a shape to find its wave</h1>"
            "<p>Tap any shape on your photo and we'll tell you which wave builds "
            "it — and light up every other shape made in that same wave.</p>"
            "<p class='muted'><a href='/'>Back to your review list</a> · "
            "<a href='/waves'>See the waves</a></p></header>"
            "<main>"
            f"<div class='readout' id='readout'>Tap a shape on your photo to "
            "see which wave it belongs to.</div>"
            "<div class='panes'>"
            "<div class='pane'><h2 style='font-family:var(--serif)'>Your photo</h2>"
            f"<div class='stage'><img src='/reference.jpg' alt='your photo'>{overlay}</div></div>"
            "<div class='pane'><h2 style='font-family:var(--serif)'>Our finished drawing</h2>"
            f"<div class='stage'>{right_img}</div>"
            "<p class='muted soon'>Tap-a-shape on our drawing is coming next — "
            "we're teaching it which drawn shape belongs to which wave.</p></div>"
            "</div></main>"
            f"{script}</body></html>"
        )

    def hub_html() -> str:
        # The front door: read session.json's stage gates and say, in plain
        # words, what needs the owner's eyes — one card per gate, done gates
        # dimmed. No jargon, no Q-numbers, no file paths in the headline.
        s = session()
        gates = s.get("stage_gates", {})
        wp = gates.get("structure", {}).get("wave_plan", {})
        plan_agreed = bool(wp.get("agreed"))
        palette_agreed = bool(gates.get("color", {}).get("palette_agreed"))
        adjudications = wp.get("open_adjudications", "")

        todo = []
        if not plan_agreed:
            extra = ""
            if adjudications:
                extra = (
                    "<p class='muted'>Two groupings we weren't sure about — "
                    "please check them on the plan page (click a shape in the "
                    "group, then move its whole group if we got it wrong):</p>"
                    f"<ul class='muted'><li>{html.escape(adjudications)}</li></ul>"
                )
            todo.append(
                "<div class='gate'><h2>1 — The building plan"
                "<span class='badge open'>needs you</span></h2>"
                "<p>We broke your picture into a few flowers, copied in waves. "
                "Look it over, fix any shape that's in the wrong group, and "
                "press “The plan looks right” when you agree — we "
                "don't start building until then.</p>"
                f"{extra}"
                "<a class='go' href='/plan'>Open the plan</a></div>"
            )
        else:
            todo.append(
                "<div class='gate done'><h2>1 — The building plan"
                "<span class='badge done'>agreed ✓</span></h2>"
                "<p>You agreed to the plan — building is underway. You can "
                "still <a href='/plan'>look at it</a>.</p></div>"
            )
        waves_passed = gates.get("structure", {}).get("waves_passed", {})
        if plan_agreed:
            n_built = len(waves_passed)
            todo.append(
                "<div class='gate'><h2>The build, wave by wave"
                "<span class='badge done'>live</span></h2>"
                f"<p>{n_built} waves are built so far. See each one beside "
                "your picture — no verdict needed, just watch.</p>"
                "<a class='go' href='/iterate'>Watch the build</a></div>"
            )
        if plan_agreed and waves_passed:
            todo.append(
                "<div class='gate'><h2>The story, slide by slide"
                "<span class='badge done'>live</span></h2>"
                "<p>The same build as a slideshow — one slide per finished "
                "wave, ending with where we are now. Lean back and tap "
                "through.</p>"
                "<a class='go' href='/slides'>Play the slideshow</a></div>"
            )
            todo.append(
                "<div class='gate'><h2>The waves, one by one"
                "<span class='badge done'>live</span></h2>"
                "<p>Every wave on one page: your photo zoomed to that wave's "
                "shapes, our build of them, just that wave's shapes on white, and "
                "the recipe lines that drew them.</p>"
                "<a class='go' href='/waves'>See the waves</a></div>"
            )
            todo.append(
                "<div class='gate'><h2>Find a shape's wave"
                "<span class='badge done'>live</span></h2>"
                "<p>Your photo beside our finished drawing — tap any shape on "
                "either one and we'll tell you which wave builds it.</p>"
                "<a class='go' href='/inspect'>Tap a shape</a></div>"
            )
        if (analysis_dir / "swatch-sheet.png").exists():
            if not palette_agreed:
                todo.append(
                    "<div class='gate'><h2>2 — The colours"
                    "<span class='badge open'>needs you</span></h2>"
                    "<p>These are the exact colours we'll paint with. One "
                    "look — are they right?</p>"
                    "<a class='go' href='/palette'>Check the colours</a></div>"
                )
            else:
                todo.append(
                    "<div class='gate done'><h2>2 — The colours"
                    "<span class='badge done'>agreed ✓</span></h2>"
                    "<p>Colours agreed. You can still "
                    "<a href='/palette'>see them</a>.</p></div>"
                )
        n_open = sum("needs you" in t for t in todo)
        head = (
            f"{n_open} thing{'s' if n_open != 1 else ''} need your eyes today."
            if n_open
            else "Nothing waiting on you right now — everything you've agreed to is underway."
        )
        return (
            "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            f"<title>Your review list</title><style>{HUB_CSS}</style></head><body>"
            f"<header><h1>Your review list</h1><p>{head}</p>"
            f"<p class='muted'>Pattern: {html.escape(s.get('name', ''))}</p></header>"
            f"<main>{''.join(todo)}</main></body></html>"
        )

    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *a, **k):
            super().__init__(*a, directory=str(plan_dir), **k)

        # Pictures change on every Apply; the browser must never show a stale
        # wave/flower PNG after a regeneration.
        def end_headers(self):
            self.send_header("Cache-Control", "no-store")
            super().end_headers()

        def _send_html(self, body: str) -> None:
            data = body.encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def _send_ok(self) -> None:
            body = b'{"ok": true}'
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            if self.path in ("/", "/index.html"):
                self._send_html(hub_html())
                return
            if self.path == "/iterate":
                self._send_html(iterate_html())
                return
            if self.path == "/slides" or self.path.startswith("/slides?"):
                # reveal.js routes its deck position via the URL hash/query;
                # both land here.
                self._send_html(slides_html())
                return
            if self.path == "/current-best.png":
                it = best_iter()
                if it is None:
                    self.send_error(404)
                    return
                # cairosvg raster is canonical from iter 49; older bests only
                # have the magick raster.
                p = session_dir / "iterations" / str(it) / "render.cairo.png"
                if not p.exists():
                    p = session_dir / "iterations" / str(it) / "render.png"
                if not p.exists():
                    self.send_error(404)
                    return
                data = p.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            if self.path == "/reference.jpg":
                p = session_dir / "input" / "reference.jpg"
                if not p.exists():
                    self.send_error(404)
                    return
                data = p.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/jpeg")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            # History thumbnail: /gate/<wave>/<iter>/sbs.png — one specific
            # past iteration of a wave (the filmstrip frames). 4 path parts
            # after the leading slash; checked BEFORE the 3-part latest route.
            if (self.path.startswith("/gate/") and self.path.endswith("/sbs.png")
                    and len(self.path.strip("/").split("/")) == 4):
                parts = self.path.strip("/").split("/")  # ["gate", wave, iter, "sbs.png"]
                try:
                    wave, it = int(parts[1]), int(parts[2])
                except ValueError:
                    self.send_error(404)
                    return
                sbs = history_sbs(wave, it)
                if sbs is None:
                    self.send_error(404)
                    return
                data = sbs.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            if self.path.startswith("/gate/") and self.path.endswith("/sbs.png"):
                try:
                    wave = int(self.path.split("/")[2])
                except ValueError:
                    self.send_error(404)
                    return
                sbs = latest_gate_sbs(wave)
                if sbs is None:
                    self.send_error(404)
                    return
                data = sbs.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            if self.path == "/progress.png":
                p = session_dir / "progress.png"
                if not p.exists():
                    self.send_error(404)
                    return
                data = p.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            if self.path == "/plan":
                self.path = "/wave-plan.html"
            elif self.path == "/palette":
                gates = session().get("stage_gates", {})
                agreed = bool(gates.get("color", {}).get("palette_agreed"))
                note = note_path.read_text() if note_path.exists() else ""
                self._send_html(
                    PALETTE_HTML.replace("__CSS__", HUB_CSS)
                    .replace("__AGREED__", json.dumps(agreed))
                    .replace("__NOTE__", html.escape(note))
                )
                return
            elif self.path == "/swatch-sheet.png":
                # The swatch sheet lives one level above the served plan dir.
                data = (analysis_dir / "swatch-sheet.png").read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            if self.path == "/waves":
                self._send_html(waves_html())
                return
            if self.path == "/inspect":
                self._send_html(inspect_html())
                return
            if self.path == "/wave-options":
                # Renamed to /waves (owner, 2026-06-15: "i don't want a
                # 'wave-options' page ... rather a waves page"). Redirect so old
                # links/bookmarks still land.
                self.send_response(301)
                self.send_header("Location", "/waves")
                self.end_headers()
                return
            # Per-wave ghost images + the option-strip comparisons live in the
            # iteration dir, outside the served plan_dir — serve them by name.
            if self.path.startswith("/wave-ghosts/"):
                name = self.path.split("/wave-ghosts/", 1)[1].split("?")[0]
                if "/" in name or ".." in name or not name.endswith(".png"):
                    self.send_error(404)
                    return
                it = best_iter()
                p = session_dir / "iterations" / str(it) / "wave-ghosts" / name
                if not p.exists():
                    self.send_error(404)
                    return
                data = p.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "image/png")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return
            super().do_GET()

        def _read_body(self) -> bytes:
            n = int(self.headers.get("Content-Length", 0))
            return self.rfile.read(n)

        def do_POST(self):
            if self.path == "/api/overrides":
                data = json.loads(self._read_body())
                # Drop empty maps so a fully-undone state deletes cleanly.
                data = {k: v for k, v in data.items() if v}
                ov = plan_dir / "wave-plan-overrides.json"
                if data:
                    ov.write_text(json.dumps(data, indent=2))
                elif ov.exists():
                    ov.unlink()
                try:
                    regen()
                except subprocess.CalledProcessError as e:
                    self.send_error(500, f"plan regeneration failed: {e}")
                    return
                self._send_ok()
            elif self.path == "/api/refresh-pictures":
                # Owner-triggered rebuild of every wave/progress picture from
                # the current renders. WHY this exists: the progress strip and
                # the per-wave thumbnails are baked PNGs (plan-waves.py output),
                # so after the loop ships a new iteration they go stale until a
                # regen runs. This button forces that regen on demand instead of
                # making the owner restart the server.
                self._read_body()
                try:
                    regen()
                    rebuild_progress_strip()
                except subprocess.CalledProcessError as e:
                    self.send_error(500, f"picture refresh failed: {e}")
                    return
                except Exception as e:  # strip rebuild is best-effort
                    self.send_error(500, f"progress strip rebuild failed: {e}")
                    return
                self._send_ok()
            elif self.path == "/api/agree":
                # The wave-plan gate verdict, recorded where the loop reads it
                # (session.json) — no chat transcription step.
                self._read_body()
                s = session()
                wp = s["stage_gates"]["structure"]["wave_plan"]
                wp["agreed"] = True
                wp["agreed_date"] = date.today().isoformat()
                save_session(s)
                self._send_ok()
            elif self.path == "/api/wave-view-pick":
                # The owner's per-wave view pick, recorded where the loop reads
                # it (session.json -> stage_gates.structure.wave_view_choices,
                # a {wave_str: view_key} map). view ∈ {"ref","ours","iso"}; the
                # stable option id the owner sees is f"w{wave}.{view}". This is
                # NOT a stage-gate approval — just which picture to show per ring.
                data = json.loads(self._read_body())
                view = data.get("view", "")
                wave = str(data.get("wave", "")).strip()
                if view not in ("ref", "ours", "iso"):
                    self.send_error(400, "view must be 'ref', 'ours', or 'iso'")
                    return
                if not wave.isdigit():
                    self.send_error(400, "wave must be a wave number")
                    return
                s = session()
                st = s["stage_gates"]["structure"]
                choices = st.setdefault("wave_view_choices", {})
                choices[wave] = view
                st["wave_view_choices_date"] = date.today().isoformat()
                save_session(s)
                self._send_ok()
            elif self.path == "/api/palette-agree":
                self._read_body()
                s = session()
                c = s["stage_gates"]["color"]
                c["palette_agreed"] = True
                c["approved_date"] = date.today().isoformat()
                save_session(s)
                self._send_ok()
            elif self.path == "/api/palette-note":
                note = self._read_body().decode()
                if note.strip():
                    note_path.write_text(note)
                elif note_path.exists():
                    note_path.unlink()
                self._send_ok()
            elif self.path == "/api/wave-verdict":
                # The owner's per-wave call, recorded where the loop reads it
                # (session.json waves_passed[n].owner_verdict) — no chat
                # transcription. state ∈ {"approved","denied",""}; an empty
                # state with a note is a comment-only save. When EVERY built
                # wave is approved, the structure stage auto-flips to approved
                # (the owner asked for per-wave only — the stage gate is a
                # derived rollup, not a separate button).
                data = json.loads(self._read_body())
                wave = str(int(data["wave"]))
                state = data.get("state", "")
                note = (data.get("note") or "").strip()
                s = session()
                wp = s["stage_gates"]["structure"].get("waves_passed", {})
                if wave not in wp:
                    self.send_error(404, f"wave {wave} not built")
                    return
                wp[wave]["owner_verdict"] = {
                    "state": state,
                    "note": note,
                    "date": date.today().isoformat(),
                }
                # Derived stage rollup: approved only when every built wave is
                # approved; a single deny (or any un-judged wave) leaves it open.
                struct = s["stage_gates"]["structure"]
                states = [(v.get("owner_verdict") or {}).get("state") for v in wp.values()]
                if states and all(st == "approved" for st in states):
                    struct["approved"] = True
                    struct["approved_at_iter"] = max(
                        (v.get("iter") for v in wp.values() if isinstance(v.get("iter"), int)),
                        default=None,
                    )
                    struct["approved_date"] = date.today().isoformat()
                else:
                    struct["approved"] = None
                    struct["approved_at_iter"] = None
                save_session(s)
                self._send_ok()
            else:
                self.send_error(404)

        def log_message(self, fmt, *a):  # quiet: one line per request is noise
            pass

    if not (plan_dir / "wave-plan.html").exists():
        print("no wave-plan.html yet — generating the plan first…")
        regen()

    print(f"Review hub: http://127.0.0.1:{args.port}/")
    print("It lists what needs your eyes; each item links to its page. Ctrl-C to stop.")
    # Threading is load-bearing: a browser keep-alive connection on a plain
    # HTTPServer holds the single handler slot and every other client times out.
    ThreadingHTTPServer(("127.0.0.1", args.port), Handler).serve_forever()


if __name__ == "__main__":
    main()
